/**
 * 365 frases sobre finanzas — una por día del año.
 *
 * Rotan determinísticamente por día-del-año.
 *
 * Tono: estoico moderno, imperativo suave, 2ª persona, sin fluff
 * motivacional ni hustle porn. Realidad práctica, no fantasía.
 *
 * Cobertura: ahorro · deuda · ingresos · gastos · inversión · riesgo
 *            · mentalidad de abundancia vs escasez (sin espiritualismo
 *            barato) · presupuesto · impuestos · flujo de caja ·
 *            inflación · lujo vs libertad · trabajo honesto · precio
 *            vs valor · tiempo como capital · oportunidad · paciencia.
 *
 * Las referencias (autor) son opcionales — solo cuando es cita real
 * verificable. Si inventas o es tuya, usa `author: null`.
 *
 * Para actualizar: sobrescribe este array antes del 30-dic. La app
 * envía un recordatorio a contacto@estoicismodigital.com esa fecha.
 */

export type FinanceQuote = {
  /** Frase, 60-180 caracteres ideal. Max 240. */
  text: string;
  /** Autor si es cita real; null si es original. */
  author: string | null;
};

export const FINANCE_QUOTES: FinanceQuote[] = [
  { text: "El dinero no resuelve lo que el carácter no ha ordenado antes.", author: null },
  { text: "Ahorrar no es renunciar: es elegir dónde quieres estar dentro de diez años.", author: null },
  { text: "No ahorres lo que te sobra después de gastar; gasta lo que te sobra después de ahorrar.", author: "Warren Buffett" },
  { text: "La deuda de consumo es un salario futuro que ya vendiste sin saberlo.", author: null },
  { text: "El presupuesto no te encierra, te muestra dónde estaban las paredes que no veías.", author: null },
  { text: "El precio es lo que pagas; el valor es lo que recibes.", author: "Warren Buffett" },
  { text: "La libertad financiera empieza el día que dejas de impresionar a desconocidos.", author: null },
  { text: "Quien gasta para aparentar, paga dos veces: una al vendedor y otra a su propia ansiedad.", author: null },
  { text: "El interés compuesto es la octava maravilla del mundo: quien lo entiende lo cobra, quien no, lo paga.", author: "Albert Einstein" },
  { text: "Invertir sin entender es apostar con pasos más lentos.", author: null },
  { text: "Tener efectivo en crisis no es cobardía: es munición para cuando todos corren.", author: null },
  { text: "La inflación es el impuesto silencioso al que ahorra mal.", author: null },
  { text: "Mide tu riqueza en meses que puedes vivir sin trabajar, no en cosas que puedes comprar.", author: null },
  { text: "No te hará rico el ingreso; te hará rico lo que no gastas de él.", author: null },
  { text: "La paciencia es la diferencia entre el que especula y el que construye.", author: null },
  { text: "Comprar a crédito lo que se deprecia es quemar dinero con recibo.", author: null },
  { text: "La riqueza es la capacidad de experimentar la vida en pleno control de tu tiempo.", author: "Morgan Housel" },
  { text: "Deja que tu dinero trabaje mientras duermes, o trabajarás hasta que mueras.", author: null },
  { text: "Ten miedo cuando otros son codiciosos y sé codicioso cuando otros tienen miedo.", author: "Warren Buffett" },
  { text: "Los impuestos se pagan; lamentarse por ellos es trabajo mal pagado.", author: null },
  { text: "La primera regla es no perder dinero. La segunda es no olvidar la primera.", author: "Warren Buffett" },
  { text: "La pobreza no es una cifra en la cuenta: es un hábito que nadie corrigió a tiempo.", author: null },
  { text: "El consumismo es el dolor de un vacío que ninguna compra cubre dos veces.", author: null },
  { text: "Si no puedes explicar en qué inviertes, es porque no entiendes qué arriesgas.", author: null },
  { text: "Cada euro tiene un destino. Si no se lo das tú, lo elegirá la inercia.", author: null },
  { text: "El lujo más caro es trabajar en algo que no soportas para pagar cosas que no necesitas.", author: null },
  { text: "Un fondo de emergencia no es miedo: es honestidad con el futuro.", author: null },
  { text: "Diversifica no porque dudes, sino porque sabes que el mundo no te avisa cuando cambia.", author: null },
  { text: "El mercado premia al paciente y castiga al impulsivo, sin excepción.", author: null },
  { text: "El tiempo en el mercado vence al cronometraje del mercado.", author: null },
  { text: "El dinero amplifica quién ya eres; no te convierte en nadie nuevo.", author: null },
  { text: "Controla tus gastos fijos y la vida se vuelve silenciosa.", author: null },
  { text: "La deuda para estudiar, producir o emprender, se mide en retorno. El resto, en arrepentimiento.", author: null },
  { text: "Comprar caro lo barato y barato lo caro: así se pierde dos veces.", author: null },
  { text: "La riqueza se construye despacio; la ruina llega rápido.", author: null },
  { text: "Pagarte a ti primero no es egoísmo: es mantenimiento del único motor que tienes.", author: null },
  { text: "La abundancia mental no es magia: es saber que siempre puedes generar más valor si te preparas.", author: null },
  { text: "La escasez mental hace decisiones caras, aunque el precio diga lo contrario.", author: null },
  { text: "El sueldo llega y se va; el hábito queda.", author: null },
  { text: "No confundas estilo de vida con calidad de vida.", author: null },
  { text: "Reduce lo que no usas, automatiza lo que repites, y tendrás tiempo para lo que importa.", author: null },
  { text: "Los descuentos no ahorran: lo que no compras es lo único que ahorra.", author: null },
  { text: "El crédito es una herramienta poderosa; en manos frágiles, un arma contra uno mismo.", author: null },
  { text: "Negocia tu salario: lo que no pides, nadie lo ofrece dos veces.", author: null },
  { text: "Un buen presupuesto empieza preguntando qué deseas realmente, no qué ganas.", author: null },
  { text: "El ego es el mayor gasto oculto del siglo.", author: null },
  { text: "Gasta en experiencias que no se devalúen en tu memoria.", author: null },
  { text: "Nunca pagues el precio del estatus con el dinero que te daría paz.", author: null },
  { text: "Quien mide, mejora. Quien no mide, repite los mismos errores con más intensidad.", author: null },
  { text: "El flujo de caja es sangre. El patrimonio sin flujo, estatua.", author: null },
  { text: "La libertad es más barata que el lujo: requiere menos, no más.", author: null },
  { text: "Comprar algo solo porque puedes es la forma más costosa de decir que no sabes quién eres.", author: null },
  { text: "No existe inversión segura; existe inversión comprendida.", author: null },
  { text: "Un activo te paga por existir; un pasivo te cobra por existir.", author: "Robert Kiyosaki" },
  { text: "Aprender a perder sin romperte es más rentable que ganar sin saber por qué.", author: null },
  { text: "La disciplina financiera de hoy es la tranquilidad del que duerme bien mañana.", author: null },
  { text: "Acumular sin propósito es cargar peso sin saber a dónde vas.", author: null },
  { text: "La riqueza real se nota en las decisiones que no tomas por dinero.", author: null },
  { text: "Hazte amigo del aburrimiento en tus inversiones: lo llamativo rara vez es rentable.", author: null },
  { text: "La prisa es el interés más caro del mundo.", author: null },
  { text: "Endeudarse por ansiedad es pagar dos veces: al banco y al terapeuta.", author: null },
  { text: "No todo lo que brilla se aprecia; la mayoría se deprecia el día que sale de la tienda.", author: null },
  { text: "El verdadero lujo es no tener que consultar el precio al final de mes.", author: null },
  { text: "La paciencia en bolsa no es una virtud: es la única estrategia que funciona a largo plazo.", author: null },
  { text: "Compras cosas que no necesitas con dinero que no tienes para impresionar a gente que no te importa.", author: "Chuck Palahniuk" },
  { text: "Quien controla su dinero, controla su agenda.", author: null },
  { text: "Invierte primero en tu conocimiento: es el único activo que nadie puede confiscarte.", author: null },
  { text: "La simplicidad financiera es la sofisticación final.", author: null },
  { text: "El riesgo viene de no saber lo que haces.", author: "Warren Buffett" },
  { text: "Un céntimo ahorrado es un céntimo ganado.", author: "Benjamin Franklin" },
  { text: "Aquel que pierde riquezas pierde mucho; aquel que pierde un amigo pierde más; pero aquel que pierde el ánimo lo pierde todo.", author: "Miguel de Cervantes" },
  { text: "No busques atajos: en finanzas, el atajo cobra intereses.", author: null },
  { text: "El mejor seguro es vivir debajo de tus medios.", author: null },
  { text: "La pobreza de espíritu precede a la pobreza de bolsillo.", author: null },
  { text: "Mirar gráficos cada hora no es invertir: es ansiedad con wifi.", author: null },
  { text: "El ahorro no empieza cuando ganas más; empieza cuando decides gastar distinto.", author: null },
  { text: "Un emprendimiento sin caja es un sueño con fecha de expiración.", author: null },
  { text: "Ser rico no es lo mismo que parecer rico; los primeros pasan desapercibidos.", author: "Thomas Stanley" },
  { text: "La liquidez es oxígeno: solo la notas cuando falta.", author: null },
  { text: "Elige a tus socios financieros con más cuidado que a tus parejas: cobran más barato los divorcios.", author: null },
  { text: "Lo que hoy llamas renuncia, mañana lo llamarás criterio.", author: null },
  { text: "Toda crisis es también una lista de oportunidades para el que conserva la calma.", author: null },
  { text: "Quien vive al límite de su sueldo, vive al límite de su libertad.", author: null },
  { text: "No persigas rendimientos: persigue procesos que los produzcan.", author: null },
  { text: "Endeudarse por vanidad es pagarle alquiler al ego.", author: null },
  { text: "El mejor inversor es el que no necesita revisar su cartera cada día.", author: null },
  { text: "Cada decisión de gasto es una apuesta sobre quién quieres ser.", author: null },
  { text: "Gastar menos no es mezquindad: es respeto por tu yo futuro.", author: null },
  { text: "Un presupuesto honesto duele al principio, pero libera al final.", author: null },
  { text: "La deuda no desaparece por ignorarla; solo engorda.", author: null },
  { text: "Las tarjetas de crédito son cuchillos afilados: útiles si sabes usarlas, peligrosas si no.", author: null },
  { text: "Vivir sin deudas no es vivir poco: es vivir sin cadenas.", author: null },
  { text: "El riesgo se mide por lo que pierdes si te equivocas, no por lo que ganas si aciertas.", author: null },
  { text: "Un ingreso alto no te convierte en rico; un gasto contenido sí.", author: null },
  { text: "La mejor inversión suele ser pagar la deuda más cara.", author: "Charlie Munger" },
  { text: "No sigas al rebaño: cuando todos corren a lo mismo, la oportunidad ya murió.", author: null },
  { text: "El miedo a perder, bien calibrado, es el mejor gestor de riesgo.", author: null },
  { text: "El pánico es un mal consejero y un pésimo corredor de bolsa.", author: null },
  { text: "Quien compra calidad, llora una vez; quien compra barato, llora cada vez que se rompe.", author: null },
  { text: "La paz mental es el dividendo más subestimado.", author: null },
  { text: "Nadie se hizo pobre por ahorrar; muchos se arruinaron por gastar de más.", author: null },
  { text: "La economía personal es 80% psicología y 20% matemáticas.", author: "Morgan Housel" },
  { text: "No te preguntes cuánto cuesta; pregúntate cuántas horas de tu vida pagas por ello.", author: null },
  { text: "Cada euro es una hora tuya convertida en número. Gástalas con intención.", author: null },
  { text: "Gasta como quien conoce el valor del tiempo y ahorra como quien conoce su fragilidad.", author: null },
  { text: "Si dependes de un solo ingreso, tu libertad depende de un solo jefe.", author: null },
  { text: "Diversificar ingresos no es hustle: es sentido común en un mundo cambiante.", author: null },
  { text: "El ego subestima la suerte; la humildad la convierte en estrategia.", author: null },
  { text: "No todo lo medible importa, pero lo que importa suele ser medible.", author: null },
  { text: "Aprender de tus errores financieros es más barato que repetirlos.", author: null },
  { text: "La abundancia empieza cuando dejas de pensar en lo que te falta y empiezas a construir con lo que tienes.", author: null },
  { text: "La meta no es morir rico; es vivir libre.", author: null },
  { text: "El buen dinero sigue al buen carácter; el mal dinero, al mal hábito.", author: null },
  { text: "No mezcles emoción con inversión: una paga caro los errores de la otra.", author: null },
  { text: "Si tu plan financiero depende de la suerte, no tienes plan.", author: null },
  { text: "Automatiza lo bueno: la disciplina delegada a tu banco no se cansa.", author: null },
  { text: "Compra tiempo, no objetos. El tiempo no se deprecia.", author: null },
  { text: "La verdadera pobreza es la incapacidad de decir no.", author: null },
  { text: "Todo precio alto tiene una hora cara detrás. Paga solo lo que vale esa hora.", author: null },
  { text: "Nunca arriesgues lo que necesitas por lo que deseas.", author: "Warren Buffett" },
  { text: "La bolsa es un mecanismo para transferir dinero del impaciente al paciente.", author: "Warren Buffett" },
  { text: "No calcules el coste solo en dinero; calcula también el coste en atención y tranquilidad.", author: null },
  { text: "Si no puedes permitírtelo dos veces, no puedes permitírtelo.", author: null },
  { text: "La prisa por enriquecerse suele ser la ruta más rápida al déficit.", author: null },
  { text: "Comprender tu relación con el dinero es entender tu relación contigo.", author: null },
  { text: "Vivir por debajo de tus medios no es vivir poco: es dejar espacio para la vida.", author: null },
  { text: "Gastar para olvidar es la forma más cara de no procesar lo que sientes.", author: null },
  { text: "El dinero ordenado calma la mente desordenada.", author: null },
  { text: "La ansiedad financiera suele ser información útil si la escuchas a tiempo.", author: null },
  { text: "Reduce la fricción del ahorro, aumenta la fricción del gasto.", author: null },
  { text: "El consumo compulsivo es una conversación que nunca tuviste contigo.", author: null },
  { text: "Cuanto más sabes, menos pagas por lo que no necesitas.", author: null },
  { text: "El lujo obediente es esclavitud con tarjeta dorada.", author: null },
  { text: "El dinero bien usado multiplica opciones; mal usado, las reduce.", author: null },
  { text: "Vigila tus pequeños gastos: un pequeño agujero hunde un gran barco.", author: "Benjamin Franklin" },
  { text: "La paciencia es capital. Úsala para comprar lo que otros venden en pánico.", author: null },
  { text: "Conoce el coste real de tu vida actual: es el mínimo que necesitas para dormir tranquilo.", author: null },
  { text: "Un buen ingreso mal gestionado se evapora; un ingreso modesto bien administrado se multiplica.", author: null },
  { text: "Renegociar es trabajar. Cada llamada para rebajar una factura es dinero ganado.", author: null },
  { text: "No trabajes por dinero: aprende a que el dinero trabaje para ti.", author: "Robert Kiyosaki" },
  { text: "Un portafolio aburrido es un portafolio sano.", author: null },
  { text: "Gastar menos de lo que ganas es simple, no fácil. Ahí vive la diferencia.", author: null },
  { text: "Invertir es posponer gratificación hoy para agradecértelo mañana.", author: null },
  { text: "La mayor parte de los errores financieros son errores emocionales con camiseta racional.", author: null },
  { text: "Quien ha dejado de aprender hoy, será pobre mañana.", author: null },
  { text: "Nada hay tan desalentador como la facilidad de hacerse pobre por costumbre.", author: null },
  { text: "Sé dueño de tu calendario antes de intentar ser dueño de tu portafolio.", author: null },
  { text: "La libertad empieza el día que tus activos cubren tu estilo de vida.", author: null },
  { text: "Quien se financia solo con deuda, alquila su vida al prestamista.", author: null },
  { text: "La riqueza sin salud es un archivo Excel con mejor tipografía.", author: null },
  { text: "Piensa como propietario, no como consumidor. Compra participación en lo que usas.", author: "Naval Ravikant" },
  { text: "El apalancamiento sin responsabilidad es la ruina acelerada.", author: null },
  { text: "Invertir en ti paga dividendos imposibles de diversificar.", author: "Warren Buffett" },
  { text: "El hábito financiero es más poderoso que el sueldo alto.", author: null },
  { text: "El ahorro diario es pequeño, pero la vida es larga.", author: null },
  { text: "Los ricos compran activos; los pobres compran pasivos disfrazados de activos.", author: "Robert Kiyosaki" },
  { text: "El dinero amplía tus decisiones; no las sustituye.", author: null },
  { text: "Tus decisiones de gasto dicen más de tus valores que tus declaraciones.", author: null },
  { text: "Cuida los céntimos, que los euros se cuidan solos.", author: null },
  { text: "La disciplina es la herramienta más subestimada en la construcción de riqueza.", author: null },
  { text: "Antes de invertir en lo próximo, comprende lo actual.", author: null },
  { text: "Comprender tu punto de equilibrio mensual es el primer paso para salir de la rueda.", author: null },
  { text: "Las decisiones financieras importantes rara vez deberían tomarse deprisa.", author: null },
  { text: "Tu historial bancario es un diario honesto de tus prioridades.", author: null },
  { text: "Vivir con menos te prepara para tener más sin perderte.", author: null },
  { text: "Las prisas no producen rendimientos; producen comisiones.", author: null },
  { text: "La clave no es predecir el mercado, es sobrevivirlo.", author: null },
  { text: "Sé conservador con lo que no puedes permitirte perder, y audaz con lo que puedes.", author: null },
  { text: "La economía doméstica es la única economía que puedes controlar por completo.", author: null },
  { text: "Cada factura cuenta una parte de tu historia. Léela antes de pagarla.", author: null },
  { text: "Los pequeños ahorros son el cemento invisible de las grandes fortunas.", author: null },
  { text: "Gasta en lo que usas, no en lo que cuentas.", author: null },
  { text: "La planificación no elimina la incertidumbre; la vuelve manejable.", author: null },
  { text: "Una hora de educación financiera evita años de errores evitables.", author: null },
  { text: "El buen momento para ahorrar fue hace diez años; el segundo mejor es hoy.", author: null },
  { text: "No confundas volatilidad con riesgo: la primera es ruido, el segundo es daño.", author: null },
  { text: "Invierte en lo que entiendes. Si no lo entiendes, sigue aprendiendo, no comprando.", author: "Peter Lynch" },
  { text: "Pagar intereses es alquilar el dinero: asegúrate de que el alquiler valga el espacio.", author: null },
  { text: "Las mejores decisiones se toman lentas; las peores, rápidas.", author: null },
  { text: "Paga las deudas pequeñas para ganar impulso; luego ataca las grandes con disciplina.", author: "Dave Ramsey" },
  { text: "No te enamores de tus inversiones: un activo es un activo, no una identidad.", author: null },
  { text: "Confianza sin humildad es una quiebra con traje nuevo.", author: null },
  { text: "La información barata no sustituye al juicio propio.", author: null },
  { text: "La envidia es el combustible de las peores decisiones financieras.", author: "Charlie Munger" },
  { text: "Un presupuesto sin meta es un mapa sin destino.", author: null },
  { text: "Cuida tu crédito: es una carta de recomendación silenciosa ante el sistema.", author: null },
  { text: "La riqueza real se cocina con rutinas, no con sprints.", author: null },
  { text: "El dinero no garantiza éxito, pero multiplica opciones para construirlo.", author: null },
  { text: "Di no a lo bueno para poder decir sí a lo excelente.", author: null },
  { text: "La mejor manera de predecir el futuro financiero es diseñarlo hoy.", author: null },
  { text: "Las finanzas personales no son una película; son una serie diaria.", author: null },
  { text: "El dinero suele huir de quien lo trata mal y queda con quien lo respeta.", author: null },
  { text: "El sueldo es un inicio; la inversión es un destino.", author: null },
  { text: "El margen es el colchón invisible que te protege del golpe inesperado.", author: null },
  { text: "No persigas rendimientos ajenos: no conoces su riesgo, sus comisiones ni sus miedos.", author: null },
  { text: "El que corre tras el dinero, corre siempre detrás.", author: null },
  { text: "Invertir es pensar en generaciones, especular es pensar en semanas.", author: null },
  { text: "La mejor protección contra la inflación es aprender a producir valor.", author: null },
  { text: "El consumo consciente es un acto político y personal al mismo tiempo.", author: null },
  { text: "Saber qué no comprar vale más que saber qué comprar.", author: null },
  { text: "Lo caro de las emergencias no es su precio; es no estar preparado.", author: null },
  { text: "Un seguro adecuado es el precio del sueño tranquilo.", author: null },
  { text: "No confundas trabajar mucho con trabajar bien pagado.", author: null },
  { text: "La productividad sin dirección financiera es correr en una cinta.", author: null },
  { text: "El primer millón es el más difícil porque el primer hábito es el más duro.", author: null },
  { text: "No inviertas para contárselo a otros; invierte para no tener que contárselo a nadie.", author: null },
  { text: "El lujo se deprecia; la paz se acumula.", author: null },
  { text: "Quien sabe renunciar, sabe elegir.", author: null },
  { text: "Todo patrimonio sin disciplina vuelve a su dueño original.", author: null },
  { text: "Las crisis no crean perdedores ni ganadores: revelan quiénes ya lo eran.", author: null },
  { text: "Un plan financiero claro es un acto de amor con tu yo futuro.", author: null },
  { text: "Los grandes ingresos no curan los malos hábitos; los amplifican.", author: null },
  { text: "No hay inversión mágica. Existe tiempo, paciencia y consistencia.", author: null },
  { text: "El mejor momento para plantar un árbol fue hace veinte años; el segundo mejor, ahora.", author: "Proverbio chino" },
  { text: "Si tu dinero no tiene propósito, otros le darán uno.", author: null },
  { text: "El orden financiero libera cabeza para crear, amar y descansar.", author: null },
  { text: "Domestica tu consumo y domesticarás tu vida.", author: null },
  { text: "El mayor enemigo del inversor es él mismo en un mal día.", author: "Benjamin Graham" },
  { text: "El mercado no siempre es lógico, pero a largo plazo premia lo sensato.", author: null },
  { text: "Nadie te enseñó economía personal porque nadie te quería libre de verdad.", author: null },
  { text: "Si quieres libertad, diseña tu salida antes de aceptar la entrada.", author: null },
  { text: "El capital humano es el único que crece cuando lo usas.", author: null },
  { text: "Cada trabajo es también una escuela: cobra, aprende y acumula valor.", author: null },
  { text: "Una deuda pagada es un salario liberado para siempre.", author: null },
  { text: "El dinero ahorrado sin propósito se gasta con cualquier excusa.", author: null },
  { text: "Si sabes vivir con poco, el mundo te cobra menos miedo.", author: null },
  { text: "Trabajar por un sueldo es necesario; depender para siempre del sueldo es frágil.", author: null },
  { text: "La libertad financiera se construye con decisiones minúsculas repetidas.", author: null },
  { text: "Más vale pobre con salud que rico con ansiedad.", author: null },
  { text: "El trabajo honesto es el cimiento que ninguna moda derriba.", author: null },
  { text: "La estrategia es importante; la ejecución es decisiva.", author: null },
  { text: "No hay ingreso pasivo sin trabajo activo previo.", author: null },
  { text: "Si te sobra dinero y te falta tiempo, algo estás midiendo mal.", author: null },
  { text: "Deja de competir con los Jones y empieza a colaborar con tu propio futuro.", author: null },
  { text: "Cuanto más complejo el producto financiero, más ciudados pide su letra pequeña.", author: null },
  { text: "Aprende a leer un contrato como quien lee un mapa de minas.", author: null },
  { text: "El control es imposible; la preparación, no.", author: null },
  { text: "Las decisiones pequeñas de hoy serán la geografía de tu vida dentro de diez años.", author: null },
  { text: "Quien entiende qué quiere, gasta menos sin esfuerzo.", author: null },
  { text: "No confundas consumo con descanso ni compras con terapia.", author: null },
  { text: "El precio del silencio financiero es la libertad mental.", author: null },
  { text: "El mercado abre cada día; tu paciencia, también.", author: null },
  { text: "El margen de seguridad es la humildad convertida en estrategia.", author: "Benjamin Graham" },
  { text: "Un patrimonio modesto bien gestionado vale más que una fortuna mal llevada.", author: null },
  { text: "No todo el que parece rico lo es, ni todo el que parece pobre lo sigue siendo.", author: null },
  { text: "Los grandes errores financieros suelen vestirse de oportunidad urgente.", author: null },
  { text: "La avaricia y la prisa son los dos peores asesores del inversor.", author: null },
  { text: "No contrates productos que no entenderías explicar a tu madre.", author: null },
  { text: "Un plan escrito se cumple más que uno pensado.", author: null },
  { text: "El rendimiento importa, pero la constancia importa más.", author: null },
  { text: "Tu sueldo no es un techo: es una pista de despegue si la respetas.", author: null },
  { text: "Repara antes de comprar, reutiliza antes de reparar, y piensa antes de repetir.", author: null },
  { text: "La vanidad es la piedra más cara del edificio financiero.", author: null },
  { text: "El trabajo duro sin dirección financiera es motor sin timón.", author: null },
  { text: "Lo barato no siempre es ahorro; a veces es gasto futuro camuflado.", author: null },
  { text: "La mente abundante reconoce oportunidades; la mente escasa, amenazas.", author: null },
  { text: "Vivir con propósito reduce gastos porque reduce deseos innecesarios.", author: null },
  { text: "Las decisiones financieras son espejos del carácter: no mienten en el extracto.", author: null },
  { text: "Evita las modas financieras: casi todas caducan antes que tu ahorro.", author: null },
  { text: "No compres oportunidades; compra activos comprendidos.", author: null },
  { text: "El rendimiento promedio sostenido vence al rendimiento brillante intermitente.", author: null },
  { text: "Quien domina su gasto, domina su destino.", author: null },
  { text: "Tu capacidad de esperar es directamente proporcional a tu capacidad de enriquecerte.", author: null },
  { text: "La seguridad financiera no la dan los ingresos, la dan los hábitos.", author: null },
  { text: "Gastar bien es invertir en ti; gastar mal es invertir en el otro.", author: null },
  { text: "Si duermes mal por dinero, algo tienes que reestructurar antes que invertir.", author: null },
  { text: "La mejor inversión siempre es la que entiendes y puedes sostener en mal tiempo.", author: null },
  { text: "El dinero es un medio; hacer de él un fin te deja sin medios y sin fines.", author: null },
  { text: "Repite lo que funciona hasta que se vuelva aburrido; entonces habrás ganado.", author: null },
  { text: "El minimalismo no es pobreza estética; es libertad operativa.", author: null },
  { text: "Compra calidad que dure, no cantidad que estorbe.", author: null },
  { text: "Tu casa, tu coche y tus hobbies son los tres lugares donde más fácil se escapa la libertad.", author: null },
  { text: "La deuda buena produce más de lo que cuesta; la deuda mala consume más de lo que da.", author: null },
  { text: "Cada mes sin presupuesto es un mes que pierdes una oportunidad de entenderte.", author: null },
  { text: "No puedes delegar tu relación con el dinero; puedes mejorar la información que usas.", author: null },
  { text: "El mejor asesor financiero eres tú cuando te informas con humildad.", author: null },
  { text: "El ahorro rinde interés con el tiempo; el gasto rinde vacío con la factura.", author: null },
  { text: "Aprende a distinguir necesidad, gusto y capricho: en esa diferencia viaja tu libertad.", author: null },
  { text: "Haz de cada euro una herramienta, no una marca de estilo.", author: null },
  { text: "La prisa vende, la calma compra.", author: null },
  { text: "Tus finanzas reflejan lo que respetas: el silencio no miente.", author: null },
  { text: "El dinero limpio duerme tranquilo.", author: null },
  { text: "El sobregasto es una voz: dice lo que te falta por resolver.", author: null },
  { text: "Cuando la oportunidad toca, la preparación responde.", author: null },
  { text: "Las oportunidades no se buscan, se reconocen cuando llegan.", author: null },
  { text: "El coste de oportunidad es el precio que nadie cobra pero todos pagan.", author: null },
  { text: "La riqueza es una consecuencia, no una meta. La meta es la libertad.", author: null },
  { text: "Cada decisión financiera es una carta a tu yo de los 70 años.", author: null },
  { text: "El presupuesto de la familia es un acto de amor compartido.", author: null },
  { text: "Hablar de dinero en casa es entrenamiento para no perderlo afuera.", author: null },
  { text: "Si no enseñas a tus hijos finanzas, el mercado lo hará sin piedad.", author: null },
  { text: "Repite lo simple muchas veces; las cosas complejas se encargan de cobrar.", author: null },
  { text: "La frugalidad bien entendida no empobrece: concentra recursos en lo que importa.", author: null },
  { text: "Quien se compara, pierde; quien aprende, acumula.", author: null },
  { text: "Cada apuesta perdida es información pagada. Úsala.", author: null },
  { text: "Invertir es comprar pedazos de futuro con disciplina del presente.", author: null },
  { text: "Cuanto mejor conoces el precio, menos discutes con el valor.", author: null },
  { text: "La cultura del crédito rápido es la cultura del arrepentimiento lento.", author: null },
  { text: "Un fondo de emergencia no es lujo: es seguro contra pequeños terremotos.", author: null },
  { text: "Tu libertad es proporcional al número de opciones que pueden pagar tus activos.", author: null },
  { text: "La generosidad es consecuencia de la abundancia real, no de la aparente.", author: null },
  { text: "Gana, guarda, invierte, disfruta — en ese orden.", author: null },
  { text: "Vive pequeño para pensar grande; pensar grande desde el lujo raro vez sale.", author: null },
  { text: "El gasto es una emoción con factura.", author: null },
  { text: "Aprende a comprar tiempo antes que cosas.", author: null },
  { text: "El margen financiero te permite pensar antes de decidir.", author: null },
  { text: "Cada deuda saldada es una frontera ampliada.", author: null },
  { text: "Los mercados premian al sistemático, castigan al nervioso.", author: null },
  { text: "Invierte con paciencia suiza y revisa con aburrimiento japonés.", author: null },
  { text: "Los impuestos son cuota de convivencia; enfócate en optimizar, no en maldecir.", author: null },
  { text: "Lee los contratos como si alguien te estuviera pidiendo una firma cara.", author: null },
  { text: "Cuando dudes del precio, calcula cuántas horas de vida cuesta.", author: null },
  { text: "Lo urgente rara vez es importante; lo importante rara vez es urgente.", author: "Eisenhower" },
  { text: "El tiempo es el activo más valioso y el menos reembolsable.", author: null },
  { text: "La abundancia empieza por reconocer lo que ya tienes sin devaluarlo.", author: null },
  { text: "El minimalismo financiero libera agenda, no limita vida.", author: null },
  { text: "No midas éxito en coches; mide éxito en noches sin ansiedad.", author: null },
  { text: "Las ganas de consumir disminuyen cuando la vida tiene sentido.", author: null },
  { text: "La identidad financiera se construye con coherencia, no con aparentar.", author: null },
  { text: "Tu mayor activo es tu salud; el segundo, tu reputación; el tercero, tu paciencia.", author: null },
  { text: "Lo que no controlas te controla; tu dinero incluido.", author: null },
  { text: "Toma las decisiones de tu cartera cuando estés bien descansado, nunca cansado.", author: null },
  { text: "El buen inversor duerme; el especulador madruga para mirar pantallas.", author: null },
  { text: "Los atajos financieros cobran doble: tiempo y tranquilidad.", author: null },
  { text: "Invertir en índices amplios es humildad convertida en estrategia.", author: "John Bogle" },
  { text: "La comisión es el insecto silencioso que se come tu rendimiento.", author: null },
  { text: "La riqueza es opcional; la libertad es obligación con uno mismo.", author: null },
  { text: "Vive como si fueras a ahorrar mañana y ahorra como si fueras a morir sin hacerlo.", author: null },
  { text: "La simplicidad es resistencia contra un mercado que quiere tu atención.", author: null },
  { text: "No pierdas dinero por miedo a perderlo; la inacción también tiene coste.", author: null },
  { text: "Aprende a decir «no tengo tiempo para eso», incluso si lo tienes.", author: null },
  { text: "La paciencia no es pasividad: es estrategia disfrazada de calma.", author: null },
  { text: "El dinero no compra sentido; compra espacio para buscarlo.", author: null },
  { text: "Ser rico no es tener mucho, es necesitar poco.", author: "Epicteto" },
  { text: "La verdadera riqueza es la pobreza de deseos.", author: "Séneca" },
  { text: "No es pobre el que tiene poco, sino el que mucho desea.", author: "Séneca" },
  { text: "La riqueza consiste mucho más en el disfrute que en la posesión.", author: "Aristóteles" },
  { text: "El hombre más rico es el que se contenta con lo que tiene.", author: "Sócrates" },
  { text: "Si quieres ser rico, no pienses en aumentar tus bienes, sino en disminuir tu codicia.", author: "Epicuro" },
  { text: "Que tu dinero sea tu esclavo y no tu amo.", author: "Proverbio latino" },
  { text: "La frugalidad incluye todas las demás virtudes.", author: "Cicerón" },
  { text: "Más vale tener poco con paz que mucho con angustia.", author: null },
  { text: "El ocio, sin lectura, es la muerte, y la sepultura del hombre vivo.", author: "Séneca" },
  { text: "Del dinero y la verdad se habla poco porque ambos incomodan al ego.", author: null },
  { text: "Pon en orden tus finanzas y tu cabeza quedará la mitad ordenada.", author: null },
  { text: "No hay suerte estable sin hábito estable.", author: null },
  { text: "La peor deuda es la que no reconoces.", author: null },
  { text: "Invertir sin plan es soltar monedas al viento y rezar.", author: null },
  { text: "Toda promesa rápida de ganancia esconde un coste que aún no ves.", author: null },
  { text: "El dinero ajeno nunca se gasta con la misma prudencia que el propio.", author: null },
  { text: "Saber decir que no es una habilidad financiera avanzada.", author: null },
  { text: "Preocúpate por la productividad de tu dinero, no por su cantidad.", author: null },
  { text: "La seguridad financiera se mide en calma, no en cifras.", author: null },
  { text: "No hay tormenta que dure lo suficiente como para romper al disciplinado.", author: null },
  { text: "Dos cosas cuestan caras: lo barato malo y lo caro innecesario.", author: null },
  { text: "El error financiero más común es ignorar que existes como usuario.", author: null },
  { text: "El dinero bien administrado te regala lo único intocable: el tiempo.", author: null },
  { text: "Si tu dinero no te da libertad, te la quita.", author: null },
  { text: "El secreto del ahorro es aburrimiento con método.", author: null },
  { text: "Lo que no puedes sostener sin estrés, no es para ti aunque lo apruebe el banco.", author: null },
  { text: "Haz del ahorro un rito semanal; haz del gasto un acto consciente.", author: null },
  { text: "La deuda de hoy es el sueldo embargado de mañana.", author: null },
  { text: "El mejor activo que puedes tener son decisiones difíciles ya tomadas.", author: null },
  { text: "La meta no es dejar de trabajar; es poder elegir en qué trabajar.", author: null },
  { text: "No existe libertad sin fondo de emergencia.", author: null },
  { text: "Pide consejo a quien ya está donde quieres estar, no a quien opine fuerte.", author: null },
  { text: "Los gurús cobran entradas; los ricos cobran dividendos.", author: null },
  { text: "No midas tu valor por lo que ganas; mide tu paz por lo que mantienes sin ansiedad.", author: null },
  { text: "Aprende a distinguir ruido de señal: la bolsa produce ambos todo el día.", author: null },
  { text: "El dinero huye de los dramáticos y se queda con los metódicos.", author: null },
  { text: "Acumula habilidades antes que objetos; viajan mejor.", author: null },
  { text: "Tu estilo de vida es un contrato silencioso con tu yo futuro: cuida la letra pequeña.", author: null },
  { text: "No hay lujo mayor que mirar tu cuenta sin miedo.", author: null },
  { text: "Rico no es el que más tiene; es el que menos debe.", author: null },
  { text: "El mejor alquiler es el que no pagas por vivir por encima de tus medios.", author: null },
  { text: "La frugalidad bien entendida es el primer paso de la libertad.", author: null },
  { text: "Tu credibilidad es más valiosa que cualquier inversión; cuídala como un dividendo.", author: null },
  { text: "Nadie entiende tu situación mejor que tú; por eso tienes la obligación de educarte.", author: null },
  { text: "Las finanzas ordenadas son la forma menos ruidosa de decir «tengo mi vida en orden».", author: null },
  { text: "El respeto al dinero ajeno enseña a cuidar el propio.", author: null },
  { text: "Cerca del ahorro vive la tranquilidad; lejos, vive el estrés.", author: null },
  { text: "Donde va tu dinero, va tu atención, y donde va tu atención, va tu vida.", author: null },
  { text: "Si no puedes permitirte perder el 100%, no arriesgues el 100%.", author: null },
  { text: "Ser coherente entre lo que ganas y cómo vives es el lujo más barato.", author: null },
  { text: "La libertad se paga en presente con moneda que llaman disciplina.", author: null },
  { text: "Aprende a vivir sin algo antes de comprarlo: así distingues deseo de necesidad.", author: null },
  { text: "La mejor publicidad de tu prosperidad es no necesitar mostrarla.", author: null },
  { text: "La opulencia suele ser nerviosa; la suficiencia es siempre serena.", author: null },
  { text: "El único ingreso que te hace libre es el que no pide tu presencia obligatoria.", author: null },
  { text: "Lo caro no siempre impresiona; casi siempre endeuda.", author: null },
  { text: "Si compras por ansiedad, no ahorras: pospones la conversación importante.", author: null },
  { text: "Hay más paz en una cuenta ordenada que en un armario lleno.", author: null },
  { text: "Cada hábito financiero sano es un voto por tu versión futura.", author: null },
  { text: "No confundas urgencia ajena con prioridad propia en tus decisiones de dinero.", author: null },
  { text: "Apaga las notificaciones de ofertas: no ahorras comprando con descuento.", author: null },
  { text: "Cualquier plan financiero debe sobrevivir a una mala semana personal.", author: null },
  { text: "Deja un colchón entre tus ingresos y tus gastos; ahí vive la calma.", author: null },
  { text: "Cada prestación social es temporal; construye una base propia.", author: null },
  { text: "La jubilación empieza el día en que empiezas a ahorrar para ella.", author: null },
  { text: "Tu capital humano se deprecia si no lo actualizas; reinviértete.", author: null },
  { text: "Una buena red de contactos es riqueza implícita.", author: null },
  { text: "El tiempo bien invertido hoy produce intereses en lugares que no imaginas.", author: null },
  { text: "Cuida tus facturas fijas: son el esqueleto silencioso de tu libertad.", author: null },
  { text: "Las cuotas mensuales son correas; elige cuántas quieres llevar.", author: null },
  { text: "El presupuesto anual te permite ver la vida completa, no los episodios sueltos.", author: null },
  { text: "Mide el coste de tu vida actual y pregúntate si estás pagando la vida que quieres.", author: null },
  { text: "No hay segundo plato de juventud; gasta en ella con criterio, no con culpa.", author: null },
  { text: "Disfruta con lo que tienes hoy mientras siembras para lo que tendrás mañana.", author: null },
  { text: "Las finanzas saludables permiten la generosidad sostenida.", author: null },
  { text: "Los regalos más valiosos rara vez son los más caros.", author: null },
  { text: "El patrimonio sin propósito es un monumento al aburrimiento.", author: null },
  { text: "Si el dinero te hace peor persona, te has vuelto su esclavo.", author: null },
  { text: "Un buen día financiero empieza por no comprar lo que no aporta.", author: null },
  { text: "La riqueza estable se construye con pocos golpes de suerte y muchas decisiones sensatas.", author: null },
  { text: "La disciplina de hoy es el privilegio de mañana.", author: null },
  { text: "No hay plan financiero que funcione si pospones lo que ya sabes que hay que hacer.", author: null },
  { text: "Las oportunidades son como trenes: pasan, pero otro llega cuando sabes esperar.", author: null },
  { text: "El dinero es música que suena mejor sin estridencias.", author: null },
  { text: "Vive bajo tus posibilidades para no vivir sometido a ellas.", author: null },
  { text: "No pretendas enriquecerte rápido; pretende no empobrecerte nunca.", author: null },
  { text: "El miedo bien administrado se convierte en prudencia; el mal administrado, en parálisis.", author: null },
  { text: "Quien espera sin actuar, pierde; quien actúa sin pensar, también.", author: null },
  { text: "Un plan financiero revisado cada trimestre es un plan vivo.", author: null },
  { text: "La honestidad financiera contigo es requisito previo de cualquier rentabilidad real.", author: null },
  { text: "No existe mejor seguro de libertad que un ahorro constante.", author: null },
  { text: "Cuando pienses «no me lo merezco», recuerda que el dinero no pide méritos, pide método.", author: null },
  { text: "El dinero no cura traumas; los ordena para que puedas mirarlos.", author: null },
  { text: "La mejor fórmula de libertad financiera: gasta menos, gana más, invierte la diferencia.", author: null },
  { text: "Una decisión lenta hoy puede ser una vida tranquila mañana.", author: null },
  { text: "Tu yo de 70 años te observa; no le debas vergüenza.", author: null },
  { text: "Empieza pequeño, empieza ahora, empieza sin esperar aprobación.", author: null },
];
