/**
 * 365 frases sobre hábitos — una por día del año.
 *
 * Rotan determinísticamente por día-del-año (1 a 366). El 29-feb
 * en años no-bisiestos cae en el índice 365 (último); en años
 * bisiestos hace uso del hueco explícito.
 *
 * Tono: estoico moderno, imperativo suave, 2ª persona, sin fluff.
 * Cobertura: disciplina · constancia · energía · descanso · lectura
 *            · gestión del tiempo · salud · micro-progreso · identidad
 *            · recaídas · rituales · entornos · ego vs sistema.
 *
 * Las referencias (autor) son opcionales — solo cuando es cita real
 * verificable. Si inventas o es tuya, usa `author: null`.
 *
 * Para actualizar: sobrescribe este array antes del 30-dic. La app
 * envía un recordatorio a contacto@estoicismodigital.com esa fecha.
 */

export type HabitsQuote = {
  /** Frase, 60-180 caracteres ideal. Max 240. */
  text: string;
  /** Autor si es cita real; null si es original. */
  author: string | null;
};

export const HABITS_QUOTES: HabitsQuote[] = [
  { text: "El hábito no nace el día que decides cambiar; nace el tercer día que repites sin aplausos.", author: null },
  { text: "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.", author: "Aristóteles" },
  { text: "No subas la escalera pensando en el último peldaño. Sube uno. Luego otro. Así se construye cualquier cosa que valga.", author: null },
  { text: "La disciplina es elegir entre lo que quieres ahora y lo que quieres más.", author: "Abraham Lincoln" },
  { text: "Si esperas sentir ganas antes de empezar, perderás casi todos los días que te quedan.", author: null },
  { text: "Cada hábito que practicas es un voto silencioso por el tipo de persona en la que te quieres convertir.", author: "James Clear" },
  { text: "El que falla un día y retoma al siguiente gana a quien fue perfecto durante dos semanas y se rindió al mes.", author: null },
  { text: "No necesitas más motivación. Necesitas menos excepciones.", author: null },
  { text: "Primera hora del día, primera victoria del día. Protege ese tramo como si ahí viviera tu futuro.", author: null },
  { text: "La libertad no es ausencia de reglas. Es tener reglas tan claras que la decisión ya está tomada antes del ruido.", author: null },
  { text: "Ningún hombre es libre si no es dueño de sí mismo.", author: "Epicteto" },
  { text: "Quien se mueve antes de debatir consigo mismo gana quince minutos, y a veces, gana un año entero.", author: null },
  { text: "No preguntes si tienes tiempo. Pregunta qué va a ocupar el tiempo de hoy si tú no decides primero.", author: null },
  { text: "La constancia es el ingrediente invisible que separa a quien habla de cambiar de quien está cambiando.", author: null },
  { text: "Un buen hábito repetido mal es mejor que un hábito perfecto que nunca empezaste.", author: null },
  { text: "No se trata de cuánto haces el día que te sientes invencible, sino de cuánto haces el día que todo se resiste.", author: null },
  { text: "Despertarse temprano no te hace superior. Lo que haces en ese silencio, sí.", author: null },
  { text: "Lo que no programas hoy, lo programará alguien por ti: jefe, algoritmo o urgencia.", author: null },
  { text: "Cada mañana dile a tu cuerpo lo que vas a hacer. Si no le das órdenes, las recibirá del antojo.", author: null },
  { text: "Tu identidad no es lo que proclamas en enero. Es lo que sostienes en noviembre.", author: null },
  { text: "Empieza pequeño. Tan pequeño que te avergüence decir que eso es lo que haces. Y sostenlo.", author: null },
  { text: "La autodisciplina es la forma más alta de amor propio, porque te protege de la versión de ti que se rinde rápido.", author: null },
  { text: "Nadie llega a la cima por un salto. Se llega por pasos que parecen ridículos, acumulados durante años.", author: null },
  { text: "Si tu entorno tira hacia abajo, tu fuerza de voluntad no alcanza. Cambia el entorno antes que la intención.", author: null },
  { text: "Ordena tu mesa, tu cama y tu agenda. No por estética, sino porque una mente clara necesita una casa clara.", author: null },
  { text: "Repetir lo correcto cuando nadie mira es la definición más honesta de carácter.", author: null },
  { text: "No cuentes lo que vas a hacer. Hazlo durante treinta días y luego, si quieres, cuéntalo.", author: null },
  { text: "Un hábito es una promesa diaria que te haces sin necesidad de firmarla dos veces.", author: null },
  { text: "El atajo casi siempre es un rodeo disfrazado.", author: null },
  { text: "Un día malo no rompe un sistema. Dos días seguidos, sí. Por eso la regla es: nunca fallar dos veces consecutivas.", author: null },
  { text: "No pospongas tu mejor versión por esperar la motivación. La motivación llega después de moverte, casi nunca antes.", author: null },
  { text: "La calidad de tu vida futura se decide en las pequeñas decisiones que hoy te parecen insignificantes.", author: null },
  { text: "Cuida lo ordinario: el sueño, la comida, el agua, los pasos. Ahí vive el ochenta por ciento de tu energía.", author: null },
  { text: "Si puedes elegir entre una hora más de trabajo y una hora más de sueño bien descansado, elige sueño. Casi siempre.", author: null },
  { text: "El cuerpo que no se mueve se queja. El cuerpo que se mueve, obedece.", author: null },
  { text: "No te prohíbas cosas. Sustitúyelas por otras mejores. La mente se rebela contra el veto, no contra el cambio.", author: null },
  { text: "Que tu primera batalla del día la gane tu mejor versión, no tu teléfono.", author: null },
  { text: "Dormir bien no es pereza. Es infraestructura.", author: null },
  { text: "El estoicismo no es apretar los dientes. Es aceptar lo que viene y responder con hábitos en lugar de humo.", author: null },
  { text: "No se trata de no caer. Se trata de no inventarte un nuevo motivo para no levantarte mañana.", author: null },
  { text: "Tu «yo» de las once de la noche no es tu amigo. Protégelo con decisiones tomadas a las ocho.", author: null },
  { text: "Si tienes que recordar el plan cada día, el plan es demasiado complicado. Simplifica hasta que el cuerpo lo sepa.", author: null },
  { text: "Progresar uno por ciento al día, sostenido, convierte a cualquiera en experto en cuatro años.", author: null },
  { text: "No entrenas solo el músculo. Entrenas la persona que aparecerá en la crisis.", author: null },
  { text: "El dinero se pierde rápido, pero el hábito de ahorrar se pierde en un instante: basta un impulso bien disfrazado.", author: null },
  { text: "Cada vez que cumples tu palabra contigo mismo, fortaleces el único contrato que importa.", author: null },
  { text: "Comer sin pantalla no es una dieta. Es reaprender a distinguir hambre real de aburrimiento crónico.", author: null },
  { text: "La lectura diaria es un gimnasio invisible. No se ve en el espejo, se ve en las decisiones.", author: null },
  { text: "Lee treinta minutos al día. A los tres años habrás leído más libros útiles que el noventa por ciento de la gente.", author: null },
  { text: "Un libro bien elegido te ahorra diez años. Léelo despacio. Subráyalo. Discute con él.", author: null },
  { text: "No basta con saber, hay que aplicar; no basta con querer, hay que hacer.", author: "Johann Wolfgang von Goethe" },
  { text: "Estudia sin prisa, aplica sin pausa. Esa es toda la fórmula que necesitas.", author: null },
  { text: "Si un libro te cambia la semana, vuelve a él cada año. Los buenos libros cambian con quien los lee.", author: null },
  { text: "El hombre culto no es el que ha leído mucho, sino el que ha aplicado lo poco que entendió bien.", author: null },
  { text: "Toma notas a mano. La mano lenta obliga a la mente a decidir qué merece quedarse.", author: null },
  { text: "No confundas consumir contenido con estudiar. Consumir entretiene; estudiar transforma.", author: null },
  { text: "No hay vientos favorables para quien no sabe adónde va.", author: "Séneca" },
  { text: "La atención es la moneda de este siglo. El que aprende a protegerla, se vuelve rico en tiempo.", author: null },
  { text: "Cuarenta minutos de foco profundo valen más que ocho horas de atención rota.", author: null },
  { text: "Apaga notificaciones. Silencia grupos. Recupera la rara habilidad de aburrirte un rato sin buscar estímulo.", author: null },
  { text: "La concentración profunda es un superpoder en un mundo que vive en interrupciones.", author: "Cal Newport" },
  { text: "Bloquea tu mejor hora para tu trabajo más importante. Protégela con la misma seriedad con la que proteges una reunión.", author: null },
  { text: "Haz una cosa. Termínala. Después sigue. Multitarea es solo fragmentación con buena prensa.", author: null },
  { text: "Si todo es urgente, nada lo es. Define antes de correr.", author: null },
  { text: "La disciplina es recordarte a las siete de la mañana lo que decidiste a las nueve de la noche del día anterior.", author: null },
  { text: "Un ritual matutino no es una moda. Es una rampa para pasar del sueño al dominio de ti mismo sin intermediarios.", author: null },
  { text: "Agua, movimiento, respiración, claridad. En ese orden, antes de cualquier pantalla.", author: null },
  { text: "Haz tu cama. Es el primer pequeño triunfo que inclina todo el día a tu favor.", author: "William H. McRaven" },
  { text: "Si no soportas dos minutos de silencio al despertar, tampoco soportarás la hora crítica del día.", author: null },
  { text: "Empieza el día derrotando una dificultad pequeña. Así entrenas al sistema a esperar victorias.", author: null },
  { text: "Piensa en la acción como voto; piensa en el hábito como partido; piensa en la identidad como bandera.", author: null },
  { text: "No vivas para el domingo. Dale textura a cada día. Uno por uno, no por paquete.", author: null },
  { text: "La noche anterior decide la mañana. Prepara la ropa, el agua, el plan. Quítale decisiones al cansado.", author: null },
  { text: "No negocies con tu rutina. Negocias con el descanso, no con el compromiso.", author: null },
  { text: "Repite hasta aburrirte. Después repite un año más. Ahí empieza de verdad el resultado.", author: null },
  { text: "El hábito es lo que te sostiene cuando el entusiasmo se cae.", author: null },
  { text: "Cuando no sepas qué hacer, haz lo básico. Agua, pasos, sueño, trabajo verdadero.", author: null },
  { text: "Deja de esperar claridad para moverte. El movimiento es lo que trae la claridad.", author: null },
  { text: "Cambia la pregunta «¿tengo ganas?» por «¿ya es la hora?». Y hazlo.", author: null },
  { text: "Tu teléfono es la puerta por la que entra el mayor ladrón de tiempo del siglo. Ponle cerrojo.", author: null },
  { text: "Desinstalar una aplicación puede tener más impacto que tres libros de productividad.", author: null },
  { text: "Un solo momento de disciplina tranquila vale por diez arranques de motivación.", author: null },
  { text: "La identidad se construye de abajo hacia arriba: con acciones repetidas, no con afirmaciones vacías.", author: null },
  { text: "Cuando dices «soy de los que», ya no debates cada mañana si hacerlo o no.", author: null },
  { text: "Cámbiate el relato: de «estoy intentando» a «soy». La palabra «intentar» invita a fallar.", author: null },
  { text: "No eres lo que lograste. Eres lo que sostienes cuando nadie te aplaude.", author: null },
  { text: "La trampa del éxito temprano es creer que ya se puede relajar el sistema que lo produjo.", author: null },
  { text: "El ego pide resultados; el proceso pide presencia. Elige proceso, los resultados llegan de propina.", author: null },
  { text: "No te compares con quien lleva diez años haciendo esto. Compárate con el tú de hace tres meses.", author: null },
  { text: "Pequeño, continuo, honesto. Esa tríada rinde más que genialidad esporádica.", author: null },
  { text: "Tus hábitos son el promedio que pagará tu década. Ajústalos en silencio.", author: null },
  { text: "La motivación se evapora con el clima; el sistema funciona con lluvia, sol o resaca.", author: null },
  { text: "Donde no hay sistema, siempre ganará el humor del día.", author: null },
  { text: "Si fallaste ayer, no busques explicación: busca lo mínimo que puedes hacer hoy.", author: null },
  { text: "Recaer no te regresa al punto cero; solo te recuerda dónde estaba la trampa.", author: null },
  { text: "La recaída no borra el progreso. Lo borra el abandono.", author: null },
  { text: "No dramatices una caída. Dramatízalo te paraliza; levantarte te fortalece.", author: null },
  { text: "Volver al hábito al día siguiente es más importante que el día que lo hiciste perfecto.", author: null },
  { text: "No esperes a sentirte listo. Lo estarás dentro, mientras ya llevas tres semanas haciéndolo.", author: null },
  { text: "Haz el movimiento aunque sea flojo. Un entrenamiento del sesenta por ciento hecho supera al cien por ciento imaginado.", author: null },
  { text: "Lo perfecto es el enemigo del inicio.", author: null },
  { text: "Tú puedes ganar la mayoría de las batallas antes de pelearlas. Se llama preparación.", author: null },
  { text: "La disciplina iguala a la libertad. Parece paradoja; es la única ley que no falla.", author: "Jocko Willink" },
  { text: "Despertarte pronto es un acto de respeto hacia la vida que dijiste querer.", author: null },
  { text: "Nadie llega a forma con un entrenamiento espectacular; se llega con ocho mil entrenamientos decentes.", author: null },
  { text: "Un hábito se mide por su piso, no por su techo. Si el peor día funciona, el sistema funciona.", author: null },
  { text: "Hacer poco pero no fallar es mucho más potente que hacer mucho y abandonar.", author: null },
  { text: "Cuando todo arde, vuelve a lo básico: agua, movimiento, sueño, tarea uno.", author: null },
  { text: "La vida humana tiene su verdadero valor en lo breve; aprende a no desperdiciarla.", author: "Séneca" },
  { text: "El tiempo que no tienes es, en realidad, tiempo que no decides.", author: null },
  { text: "Diez minutos bien invertidos cada día son cincuenta horas al año. Eso es una habilidad nueva.", author: null },
  { text: "Aprende a decir no con calma. Cada sí mal dado es un pedazo de hábito vendido.", author: null },
  { text: "Guarda tu mañana para tu obra; la tarde es del mundo.", author: null },
  { text: "Si tu cuerpo te pide siete horas de sueño, dáselas sin sentirte culpable.", author: null },
  { text: "Comer a las mismas horas, dormir a las mismas horas, trabajar a las mismas horas. Así se construye paz.", author: null },
  { text: "Una vida simple y bien hecha vale más que una complicada y con ruido.", author: null },
  { text: "Despójate de lo que no usas. La cantidad de cosas que cargas es la cantidad de atención que pierdes.", author: null },
  { text: "La disciplina no es castigo; es la forma adulta de cuidarse.", author: null },
  { text: "Entrena cuando no tengas ganas. Ese entrenamiento, precisamente ese, te cambia el carácter.", author: null },
  { text: "No necesitas hacerlo increíble, necesitas hacerlo hoy.", author: null },
  { text: "La vida no se trata de esperar a que pase la tormenta, sino de aprender a andar bajo la lluvia.", author: null },
  { text: "Camina quince minutos después de comer. Es el truco más antiguo para la cabeza clara.", author: null },
  { text: "No puedes comprar tiempo, pero puedes comprar lentitud al elegir menos cosas.", author: null },
  { text: "El silencio no es vacío, es donde se ordena la mente.", author: null },
  { text: "Si no tienes cinco minutos para respirar, entonces necesitas veinte.", author: null },
  { text: "La fe sin disciplina es superstición. La disciplina sin fe es burocracia. Juntas, sostienen a una persona.", author: null },
  { text: "No esperes condiciones ideales. Casi nadie las tuvo. Y casi nadie lo logró esperándolas.", author: null },
  { text: "La libertad sin rutina se vuelve caos. La rutina sin propósito se vuelve cárcel. Busca el punto medio.", author: null },
  { text: "Que la repetición no te parezca monotonía. La repetición es la forma en que se talla una estatua.", author: null },
  { text: "No se trata de rendir al cien cada día, sino de asegurarte de aparecer todos los días.", author: null },
  { text: "Un año tiene tres horas al día de trabajo profundo disponible. Eso, sostenido, es más que suficiente.", author: null },
  { text: "La fuerza de voluntad es un recurso limitado. Gástala en decisiones importantes, no en debates internos.", author: null },
  { text: "Cuanto más automático, más libre. Los hábitos te compran espacio mental para lo importante.", author: null },
  { text: "No te castigues por fallar. Castígate por no tener un plan para cuando falles.", author: null },
  { text: "Sustituye el «debería» por «me comprometo a». Cambia el lenguaje y cambia la acción.", author: null },
  { text: "No te sientas culpable por descansar. Siéntete culpable si confundes descanso con evasión.", author: null },
  { text: "Descansar no es dejar de moverse. A veces es caminar lento, leer, mirar por la ventana.", author: null },
  { text: "El aburrimiento de los profesionales es el hambre de los aficionados.", author: null },
  { text: "Aprende a hacer lo importante cuando ya no es novedad. Ahí se separan los caminos.", author: null },
  { text: "La noche antes de un día difícil, prepara. La mañana del día difícil, ejecuta. Sin debates.", author: null },
  { text: "Un cronograma escrito te obedece. Uno mental te traiciona.", author: null },
  { text: "Escribe tu próxima acción. Solo una. Muévete a ella.", author: null },
  { text: "La diferencia entre soñar y construir es un calendario.", author: null },
  { text: "No pagues la renta de una cabeza desordenada. Ordena tres minutos al día; esa es toda la cuota.", author: null },
  { text: "Limpia tu espacio antes de dormir. Tu yo de mañana te lo agradecerá sin palabras.", author: null },
  { text: "La regla de los dos minutos: si algo tarda menos que eso, hazlo ahora. Si no, agéndalo.", author: "David Allen" },
  { text: "Ningún hábito resiste un entorno hostil sostenido. Diseña el entorno con la misma seriedad que el plan.", author: null },
  { text: "Deja la fruta a la vista y los dulces fuera. Así ganas medio kilo de fuerza de voluntad al año.", author: null },
  { text: "Pon los libros donde antes dejabas el mando. La arquitectura gana silenciosamente a la intención.", author: null },
  { text: "Saca el teléfono del cuarto. No hay hábito nocturno que sobreviva a una notificación.", author: null },
  { text: "El desayuno de un ganador no tiene magia; tiene constancia.", author: null },
  { text: "No confundas actividad con progreso. Sudar no es lo mismo que avanzar.", author: null },
  { text: "Mide lo que importa. Si no lo mides, lo estás deseando, no gestionando.", author: null },
  { text: "Un diario de cinco minutos te ahorra cinco horas de rumiación semanal.", author: null },
  { text: "Anota una victoria pequeña cada noche. Tres meses después, te conocerás mejor.", author: null },
  { text: "Empezar un hábito nuevo dura semanas. Asentarlo dura meses. Hacerlo identidad, años. Acepta el plazo.", author: null },
  { text: "Lo lento es lo nuevo rápido. Siempre lo fue.", author: null },
  { text: "La vida disciplinada se disfruta más, no menos. El placer sin orden pronto cansa.", author: null },
  { text: "Sé duro contigo en lo importante y blando en lo trivial. La mayoría hace al revés.", author: null },
  { text: "Cuando dudes entre descansar y empujar, mira tus últimos tres días. Si fueron honestos, descansa.", author: null },
  { text: "La mente se parece al jardín; si no plantas cosas buenas, crecerán malas.", author: null },
  { text: "Siembra conversaciones que te estiren. Los amigos que te dejan igual no son amigos; son espejos complacientes.", author: null },
  { text: "Rodearte de gente que madruga tiene más poder que cualquier libro de productividad.", author: null },
  { text: "Tu promedio es, aproximadamente, el promedio de las cinco personas con las que hablas más.", author: "Jim Rohn" },
  { text: "Elige con cuidado tus referentes. El cerebro imita aunque tú no lo notes.", author: null },
  { text: "Una familia que lee, hace ejercicio y ahorra se convierte, sin darse cuenta, en otra clase de familia.", author: null },
  { text: "Las costumbres del hogar enseñan más que las lecciones del hogar.", author: null },
  { text: "Camina mientras hablas por teléfono. Recuperas cinco kilómetros a la semana sin darte cuenta.", author: null },
  { text: "Sube escaleras. Es el gimnasio de los que no tienen tiempo de gimnasio.", author: null },
  { text: "Bebe agua antes del café. Tu cuerpo lleva ocho horas pidiéndola.", author: null },
  { text: "Treinta minutos de sol temprano equivalen a una pastilla que no existe para el humor.", author: null },
  { text: "Respirar por la nariz todo el día parece tontería; es uno de los ajustes más rentables del cuerpo.", author: null },
  { text: "Mastica despacio. Es la única dieta que funciona para casi todos.", author: null },
  { text: "Saltar comidas no te hace fuerte; dormir mal, tampoco. Las bases, primero.", author: null },
  { text: "Si no duermes, no entrenas; si no entrenas, no rindes. Todo se conecta, empieza por dormir.", author: null },
  { text: "Apágate a una hora, despiértate a una hora. El resto del sistema se alinea solo.", author: null },
  { text: "No tomes decisiones importantes después de las diez de la noche. Casi nunca salen bien.", author: null },
  { text: "La mente cansada ve tragedias donde hay solo problemas. Duérmete y vuelve a mirarlo mañana.", author: null },
  { text: "La mayoría de las grandes decisiones se posponen por hábitos mal resueltos.", author: null },
  { text: "El ahorro es un hábito, no una cantidad. Guardar poco sostenidamente supera a guardar mucho una vez.", author: null },
  { text: "Paga primero a tu yo de veinte años más adelante. Es el único acreedor que nadie te cobra.", author: null },
  { text: "Automatiza lo bueno: ahorro, lectura, entrenamiento. La voluntad es frágil; los sistemas no.", author: null },
  { text: "La libertad financiera empieza por el hábito de no fingir un nivel que no tienes.", author: null },
  { text: "El lujo más difícil de sostener es el de la calma. Constrúyela con hábitos, no con vacaciones.", author: null },
  { text: "Quien no domina su día no domina su vida.", author: null },
  { text: "Vigila tus primeros quince minutos despierto. Ahí se juega el tono emocional del día entero.", author: null },
  { text: "No leas noticias antes de trabajar. No las leas, idealmente, hasta después de mediodía.", author: null },
  { text: "Una mente que empieza el día ofendida trabajará todo el día ofendida.", author: null },
  { text: "No busques la perfección; busca terminar lo empezado hoy.", author: null },
  { text: "Termina una cosa. Después decide. Termina, decide. Así, todo.", author: null },
  { text: "Dejar a medias agota más que hacer. Cierra lazos antes de dormir.", author: null },
  { text: "La voz interna que te dice «mañana empiezo» es la misma que lleva años diciéndotelo.", author: null },
  { text: "No discutas con esa voz. Muévete. Mientras te mueves, no puede hablar.", author: null },
  { text: "Discutir con la pereza es perder el debate. Vencerla es empezar en silencio.", author: null },
  { text: "Sesenta segundos de acción valen más que sesenta minutos de análisis.", author: null },
  { text: "Cuando te enfrentas a un hábito nuevo, hazlo torpe pero hecho. La técnica llega después.", author: null },
  { text: "La mejor postura es la que todavía no has probado: la de la próxima semana.", author: null },
  { text: "Marco Aurelio se decía cada mañana: hoy me encontraré con gente inoportuna; no te sorprendas, prepárate.", author: "Marco Aurelio" },
  { text: "Empieza el día imaginando los obstáculos. Así, cuando aparecen, no te tumban.", author: null },
  { text: "No eres tu pensamiento; eres tu respuesta.", author: null },
  { text: "Aquello que te enfada te domina. El hábito de respirar antes de hablar es uno de los más rentables.", author: null },
  { text: "Que tu mejor respuesta sea retrasar treinta segundos la respuesta.", author: null },
  { text: "Si no puedes mantener un silencio de diez segundos, no puedes mantener una conversación importante.", author: null },
  { text: "Los mejores hábitos son los que sobreviven al viaje, a la enfermedad y al enojo.", author: null },
  { text: "Viaja con tu rutina en la maleta. Los cambios en el plan no deberían tumbar tus fundamentos.", author: null },
  { text: "Cuando enfermes, haz la versión mínima del hábito. No lo abandones, adáptalo.", author: null },
  { text: "La constancia suave vence al esfuerzo intermitente. Siempre.", author: null },
  { text: "La disciplina crea los momentos de los que luego presume la espontaneidad.", author: null },
  { text: "Nada bueno se construye en una tarde; nada valioso se pierde en una.", author: null },
  { text: "No te prometas el mundo. Prométete aparecer mañana a las siete. Y cúmplelo.", author: null },
  { text: "Empezar está sobrevalorado; mantener está infravalorado.", author: null },
  { text: "Quien aprende a esperar un resultado sin forzarlo, casi siempre lo consigue.", author: null },
  { text: "Tu mente y tu cuerpo son los únicos bienes que te acompañan cada día. Invierte en ellos primero.", author: null },
  { text: "El que cuida sus horas cuida su vida; el que cuida su vida la hace digna.", author: null },
  { text: "Cualquier cosa que hagas a diario durante seis meses se vuelve parte de tu carácter.", author: null },
  { text: "La paciencia no es quedarse quieto; es seguir haciendo sin ver el resultado aún.", author: null },
  { text: "La vida no te da lo que quieres, te da lo que buscas con disciplina.", author: null },
  { text: "Quien no sabe descansar, pronto no sabrá trabajar.", author: null },
  { text: "Haz del aburrimiento tu aliado. En un mundo sobreestimulado, quien tolera el silencio, ve primero.", author: null },
  { text: "Camina sin auriculares de vez en cuando. La cabeza se ordena con el paso y con el mundo hablándole.", author: null },
  { text: "Un café, una libreta y quince minutos de silencio: la tecnología más potente del siglo.", author: null },
  { text: "Haz listas cortas. Una larga te paraliza; una corta te mueve.", author: null },
  { text: "Tres tareas al día bien hechas superan a diez tareas a medias. Elige menos, cumple más.", author: null },
  { text: "La semana empieza el domingo por la tarde, cuando decides qué importa.", author: null },
  { text: "Un cuarto de hora el domingo te ahorra cinco horas perdidas entre lunes y viernes.", author: null },
  { text: "Revisa tu semana cada sábado. Sin juzgarte, sin felicitarte. Solo mira.", author: null },
  { text: "Si algo no se repite, no te dará resultados repetidos. Regla simple.", author: null },
  { text: "No creas a tu mente cuando te diga que este día es especial y puedes saltártelo. Ella siempre lo dirá.", author: null },
  { text: "El compromiso es un contrato silencioso contigo; no lo firmes con ligereza.", author: null },
  { text: "Cuanto menos hables de lo que vas a hacer, más probable es que lo hagas.", author: null },
  { text: "Silencia tus planes; que hablen tus rutinas.", author: null },
  { text: "Entrena para un día en el que todo falle. Si lo soportas, el resto son bonificaciones.", author: null },
  { text: "No eres tan disciplinado como crees hoy; lo sabrás el día que no te apetezca nada.", author: null },
  { text: "La verdadera prueba de un hábito es hacerlo sin que nadie lo note.", author: null },
  { text: "Tu futuro se decide en las decisiones pequeñas de las cinco de la tarde, cuando la energía cae.", author: null },
  { text: "Las tres de la tarde son las horas del diablo: prepara un pequeño ritual para cruzarlas limpio.", author: null },
  { text: "Come ligero al mediodía si quieres rendir por la tarde. Dieta es también estrategia.", author: null },
  { text: "Alcohol, pantallas y mala compañía: los tres sabotajes clásicos de cualquier progreso.", author: null },
  { text: "Reduce lo obvio antes de optimizar lo sofisticado.", author: null },
  { text: "Menos café, más agua. Menos scroll, más páginas. Menos fiesta, más caminatas. Aburrido, efectivo.", author: null },
  { text: "Un hábito bueno es un seguro barato contra un futuro caro.", author: null },
  { text: "No somos conscientes de la fuerza del hábito hasta el día que intentamos romperlo.", author: null },
  { text: "Nos lo recordamos cada día: pequeñas cosas, hechas con constancia, reescriben una vida.", author: null },
  { text: "La gloria del hombre no está en no caer nunca, sino en levantarse cuantas veces caiga.", author: "Confucio" },
  { text: "Todos tropiezan; pocos se levantan con método.", author: null },
  { text: "No te definas por la caída. Defínete por cómo te sacudes el polvo.", author: null },
  { text: "Ten preparado un plan B para cuando falles el plan A. La madurez es anticipar la imperfección.", author: null },
  { text: "Una cosa distingue al que avanza: empezar otra vez sin hacer drama.", author: null },
  { text: "La humildad diaria supera a la arrogancia ocasional.", author: null },
  { text: "Un hombre que cada noche sabe tres cosas que hizo bien y una que mejorar, en un año es otro.", author: null },
  { text: "Escribe tres agradecimientos cada noche. Cambia tu química antes de cerrar los ojos.", author: null },
  { text: "Gratitud practicada es el antídoto más barato contra la ansiedad.", author: null },
  { text: "El aburrimiento no es problema; evadirlo lo es. Déjalo estar, y la mente ordena.", author: null },
  { text: "Un domingo sin pantallas es un regalo que te haces a ti mismo y a tu semana siguiente.", author: null },
  { text: "Recuerda que puedes empezar tu día de nuevo a cualquier hora. No te rindas a las diez de la mañana.", author: null },
  { text: "Si fallaste el desayuno, no falles la comida. Si fallaste la mañana, no falles la tarde.", author: null },
  { text: "La vida son muchas pequeñas segundas oportunidades por día; aprende a verlas.", author: null },
  { text: "No huyas del incómodo presente buscando un futuro mejor. El presente es donde se decide.", author: null },
  { text: "Aprende a vivir el lunes como si fuese el día más importante. Casi siempre lo es.", author: null },
  { text: "No te enamores del plan. Enamórate del progreso y ajusta el plan cuando haga falta.", author: null },
  { text: "Lo mejor del proceso es que premia al que lo sigue sin buscar atajos.", author: null },
  { text: "No busques el método perfecto; el método que cumples vence al que admiras.", author: null },
  { text: "Empieza con lo que tienes, donde estés; esa es la fórmula antigua y sigue funcionando.", author: null },
  { text: "Los grandes resultados tienen detrás una decisión aburrida repetida mil veces.", author: null },
  { text: "La vida disciplinada permite la broma, el viaje, el vino. Son las vidas caóticas las que no pueden permitirse nada.", author: null },
  { text: "Disfruta lo que haces mientras lo haces. Un hábito odiado no sobrevive diciembre.", author: null },
  { text: "Busca hábitos que disfrutes, no solo los que admires. La sostenibilidad empieza por el gusto.", author: null },
  { text: "La vida es un arco; tensa solo cuando apuntas, el resto del tiempo, afloja.", author: null },
  { text: "Si tu energía sube y baja, no es fallo moral; es biología. Duerme, come, muévete, y volverá.", author: null },
  { text: "Evalúa tu día por la cama, no por el éxito. ¿Te acuestas en paz? El resto es bonus.", author: null },
  { text: "Dormir en paz contigo mismo es un lujo que la disciplina paga cada noche.", author: null },
  { text: "No hagas lo fácil ahora si te va a costar caro mañana; no hagas lo difícil ahora si mañana no va a importar.", author: null },
  { text: "Elige bien tus dificultades. Son las que te esculpen.", author: null },
  { text: "Todos los días toca un trozo de la estatua. Con paciencia aparece una obra.", author: null },
  { text: "El que se rinde en el mes tres no llega nunca al mes doce, donde está el milagro.", author: null },
  { text: "Los primeros noventa días son prueba; los siguientes noventa, transformación; el resto, vida.", author: null },
  { text: "Todo lo que merece la pena tiene una meseta larga. Cruza la meseta y gana la cumbre.", author: null },
  { text: "La gente admira el talento y paga la disciplina.", author: null },
  { text: "El talento sin hábito se agota; el hábito sin talento, llega.", author: null },
  { text: "Si tienes que elegir entre un plan complicado y uno que vas a cumplir, elige el segundo.", author: null },
  { text: "Simplifica. Tu vida quiere menos reglas, pero más sólidas.", author: null },
  { text: "Pocas reglas, siempre. Es mejor divisa que muchas reglas, a veces.", author: null },
  { text: "No necesitas controlar el día entero. Gana los primeros noventa minutos y casi todo cae solo.", author: null },
  { text: "Los primeros noventa minutos del día deberían ser los menos negociables.", author: null },
  { text: "Si empiezas mal la mañana, no arrastres el mal día entero. Ten un botón de reinicio a mediodía.", author: null },
  { text: "La diferencia entre quien avanza y quien no es que uno reinicia el día a las dos de la tarde y el otro lo da por perdido.", author: null },
  { text: "Tres entrenamientos a la semana, durante toda una década, construyen un cuerpo distinto.", author: null },
  { text: "No entrenes para verano. Entrena para los ochenta años.", author: null },
  { text: "Fuerza y movilidad a partir de los treinta no son vanidad; son seguro de vida.", author: null },
  { text: "Camina diez mil pasos, si puedes. Y si no, camina los que puedas. Mover el cuerpo es la base de mover la mente.", author: null },
  { text: "La mente sigue al cuerpo más de lo que creemos.", author: null },
  { text: "Antes de arreglar tu ánimo, arregla tu postura, tu respiración y tu agua.", author: null },
  { text: "Ansiedad muchas veces es cafeína, falta de sueño y sedentarismo disfrazados.", author: null },
  { text: "Menos pantallas en la cama: el mejor antidepresivo que casi nadie se receta.", author: null },
  { text: "La luz de la pantalla a la una de la mañana es un impuesto directo a tu yo de mañana.", author: null },
  { text: "Cierra la cocina a una hora. Después, no cenes más. La digestión agradece, el sueño agradece, el reloj agradece.", author: null },
  { text: "No se trata de comer perfecto; se trata de comer bastante bien el ochenta por ciento de las veces.", author: null },
  { text: "El ochenta por ciento consistente derrota al cien por ciento perfeccionista.", author: null },
  { text: "Lo suficientemente bueno, hecho siempre, es casi siempre mejor que lo óptimo hecho a veces.", author: null },
  { text: "Abandona el perfeccionismo de cada sesión. Quédate con la disciplina del largo plazo.", author: null },
  { text: "La grandeza no llega un martes. Se va haciendo sin avisar a nadie, ni siquiera a ti.", author: null },
  { text: "No busques sentirte orgulloso cada día; busca no avergonzarte al final del mes.", author: null },
  { text: "El orgullo es mal compañero; sustitúyelo por trabajo tranquilo.", author: null },
  { text: "Prefiere el hábito callado a la intención ruidosa.", author: null },
  { text: "Quien se pone metas pequeñas y las cumple se hace más fuerte que quien se pone metas grandes y las abandona.", author: null },
  { text: "Metas grandes, pasos pequeños, revisiones frecuentes. No es complicado.", author: null },
  { text: "Una revisión honesta semanal vale por tres meses de inercia.", author: null },
  { text: "Revisa, ajusta, continúa. Tres verbos suficientes para toda una vida.", author: null },
  { text: "La mejora del uno por ciento no impresiona a corto plazo. Pero en veinticuatro meses, es otra persona.", author: null },
  { text: "No te compares con el promedio. Compárate con tu mejor versión posible realista.", author: null },
  { text: "Ser constante es menos glamuroso que ser brillante, y muchísimo más rentable.", author: null },
  { text: "Un cuerpo que recibe buenos hábitos durante veinte años se comporta como uno de diez años menos.", author: null },
  { text: "La disciplina es un regalo que te hace tu yo futuro, si tú estás dispuesto a escribirla hoy.", author: null },
  { text: "No preguntes «¿cómo sería mi vida con este hábito en diez años?». Empieza hoy y dentro de diez lo sabrás.", author: null },
  { text: "Cada hora que proteges de la distracción vale más que cinco horas de trabajo disperso.", author: null },
  { text: "El mundo moderno te pagará por concentrarte. Casi nadie sabe hacerlo dos horas seguidas.", author: null },
  { text: "La atención es más escasa que el dinero, y quien la entrena, domina.", author: null },
  { text: "Deja el móvil en otra habitación cuando trabajes. Un gesto que parece tonto, cambia carreras.", author: null },
  { text: "Una hora sin teléfono al día te devolverá lo que llevas meses perdiendo.", author: null },
  { text: "Un entrenamiento por la mañana te da coraje para el resto del día.", author: null },
  { text: "Moverte antes de trabajar es decirle al cerebro: vengo listo.", author: null },
  { text: "Escribe lo importante a mano. La pantalla olvida; el papel recuerda.", author: null },
  { text: "Una libreta física cerca de la cama graba mejor que un cerebro somnoliento.", author: null },
  { text: "Tu futuro no se decide un día; se decide durante una semana repetida cincuenta y dos veces al año.", author: null },
  { text: "Las semanas son los ladrillos; los años son la casa. Cuida los ladrillos.", author: null },
  { text: "Una persona tranquila con rutina sólida puede con casi cualquier temporada difícil.", author: null },
  { text: "La rutina es el armazón del barco. Las olas pasan por encima sin hundirlo.", author: null },
  { text: "No dependas de la inspiración. Depende de que a las siete tienes la zapatilla puesta.", author: null },
  { text: "Primero, aparecer. Segundo, hacer. Tercero, mejorar. En ese orden.", author: null },
  { text: "Vence al yo de las seis de la mañana y el yo de las seis de la tarde te respetará.", author: null },
  { text: "Los hábitos son la forma silenciosa de llevarte respeto a ti mismo.", author: null },
  { text: "Lo que haces a las seis, a las tres de la tarde y a las diez de la noche define quién eres.", author: null },
  { text: "El tiempo que hoy regalas al móvil es el tiempo que faltará para un libro, un paseo o un abrazo.", author: null },
  { text: "Cada scroll es un pequeño trueque. Saca cuentas una vez y decide si vale la pena.", author: null },
  { text: "Dos horas menos de pantalla al día son catorce horas a la semana. Imagina qué cabes en catorce horas.", author: null },
  { text: "Empieza donde estás, con lo que tienes, haz lo que puedas.", author: "Theodore Roosevelt" },
  { text: "Cuida lo que dejas entrar: música, series, noticias, conversaciones. Te forman sin pedirte permiso.", author: null },
  { text: "Cerebro sano, cuerpo sano, finanzas sanas. Una pata floja derriba la mesa.", author: null },
  { text: "Sé disciplinado con lo que entra a tu cuenta, a tu estómago y a tu cabeza. Todo lo demás se acomoda.", author: null },
  { text: "Un café lento con un libro puede valer más que una mañana de reuniones.", author: null },
  { text: "Los lunes no los inventaron para odiarlos. Los inventaste así al no preparar el domingo.", author: null },
  { text: "El domingo es para revisar, planear y descansar. No para huir de la realidad.", author: null },
  { text: "Un sábado bien dormido supera a una fiesta tibia.", author: null },
  { text: "La amistad sobria con uno mismo es el hábito más poderoso de todos.", author: null },
  { text: "Haz las paces con tu voz interna. Mejor aún, entrénala como entrenas el cuerpo.", author: null },
  { text: "Una mente entrenada dice «sigue» cuando el cuerpo dice «un poco más».", author: null },
  { text: "Hablarte con respeto es un hábito que cambia la cara con la que miras el mundo.", author: null },
  { text: "No te digas cosas que no le dirías a un amigo. Ese pequeño ajuste cambia una vida.", author: null },
  { text: "Una disculpa contigo mismo, cuando fallas, vale más que una promesa nueva.", author: null },
  { text: "Pide perdón a tu cuerpo y vuelve a ponerte la zapatilla. Eso es madurez.", author: null },
  { text: "El alma se tiñe con el color de sus pensamientos.", author: "Marco Aurelio" },
  { text: "Piensa bien, respira hondo, muévete despacio, come limpio, duerme pronto. Todo lo demás se acomoda.", author: null },
  { text: "Haz cada día una cosa difícil y una cosa amable. Así se balancea una vida.", author: null },
  { text: "La amabilidad contigo no es blandura; es la arquitectura emocional del largo plazo.", author: null },
  { text: "El que se cuida se quiere; el que se quiere, cuida a otros mejor.", author: null },
  { text: "Primero el oxígeno para ti: ducha, desayuno, caminata. Después, el mundo.", author: null },
  { text: "Un té caliente, un libro y silencio: el lujo más barato y más sanador.", author: null },
  { text: "Aprende a sentarte contigo mismo diez minutos. Si puedes eso, puedes casi todo.", author: null },
  { text: "La paz no es ausencia de caos; es la rutina que sostienes en medio del caos.", author: null },
  { text: "Un hombre tranquilo no es un hombre sin tormentas; es un hombre con un timón.", author: null },
  { text: "El timón es tu hábito. Tómalo con las dos manos cada mañana.", author: null },
  { text: "Al final, tú eres el promedio de tus hábitos, no de tus intenciones.", author: null },
  { text: "Si lees hasta aquí, respira, cierra los ojos, y pregúntate: ¿cuál es el pequeño gesto de hoy?", author: null },
  { text: "Cualquier gesto pequeño hecho hoy te pone por delante de quien seguirá mañana planeándolo.", author: null },
  { text: "Gana el día. Después duerme. Mañana vuelves a empezar.", author: null },
];
