/**
 * 365 citas diarias — reflexiones estoicas y filosóficas.
 *
 * Una por día del año. Rotan determinísticamente. Usadas como
 * "Reflexión del día" en el módulo de hábitos.
 *
 * Todas las citas son reales y verificables. Procedencia en `source`.
 *
 * Para actualizar: sobrescribe este array antes del 30-dic. La app
 * envía un recordatorio a contacto@estoicismodigital.com esa fecha.
 */

export type HabitsQuote = {
  text: string;
  author: string | null;
  /** Libro, carta, discurso de procedencia. Ej. "Meditaciones, IV.3". */
  source?: string | null;
};

export const HABITS_QUOTES: readonly HabitsQuote[] = [
  { text: "No pierdas más tiempo discutiendo sobre cómo debe ser un hombre bueno. Sé uno.", author: "Marco Aurelio", source: "Meditaciones, X.16" },
  { text: "Toda nuestra sabiduría consiste en servil prejuicios. Nadie juzga con la cabeza; todos juzgan con el corazón.", author: "Michel de Montaigne", source: "Ensayos, I.14" },
  { text: "Nuestra vida es lo que nuestros pensamientos hacen de ella.", author: "Marco Aurelio", source: "Meditaciones, IV.3" },
  { text: "No es que tengamos poco tiempo, sino que perdemos mucho. La vida es suficientemente larga si se sabe emplearla.", author: "Séneca", source: "Sobre la brevedad de la vida, I" },
  { text: "El hombre que ha encontrado un porqué para vivir es capaz de soportar casi cualquier cómo.", author: "Viktor Frankl", source: "El hombre en busca de sentido" },
  { text: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche", source: "El crepúsculo de los ídolos, Máximas, 12" },
  { text: "No son las cosas las que atormentan a los hombres, sino las opiniones que tienen sobre ellas.", author: "Epicteto", source: "Enquiridión, 5" },
  { text: "El hombre que se atreve a desperdiciar una hora de tiempo no ha descubierto el valor de la vida.", author: "Charles Darwin", source: "Autobiografía" },
  { text: "Despiértate al amanecer con voluntad de trabajar. Lo que haces cada día es lo que eres.", author: "Marco Aurelio", source: "Meditaciones, V.1" },
  { text: "Quien vive muchos años ha vivido mucho; otros han existido mucho, pero han vivido poco.", author: "Séneca", source: "Cartas a Lucilio, 49" },
  { text: "La felicidad de tu vida depende de la calidad de tus pensamientos.", author: "Marco Aurelio", source: "Meditaciones, V.16" },
  { text: "Si quieres mejorar, estate dispuesto a parecer estúpido y necio en lo exterior.", author: "Epicteto", source: "Enquiridión, 13" },
  { text: "Conócete a ti mismo y conocerás el universo y a los dioses.", author: "Sócrates", source: "Platón, Fedro" },
  { text: "Una vida sin examen no merece ser vivida.", author: "Sócrates", source: "Platón, Apología de Sócrates, 38a" },
  { text: "El viaje de mil millas comienza con un solo paso.", author: "Lao Tzu", source: "Tao Te Ching, 64" },
  { text: "Conocer a los demás es inteligencia; conocerse a uno mismo es verdadera sabiduría. Dominar a los demás es fuerza; dominarse a uno mismo es verdadero poder.", author: "Lao Tzu", source: "Tao Te Ching, 33" },
  { text: "Todo lo que somos es el resultado de lo que hemos pensado.", author: "Buda", source: "Dhammapada, I.1" },
  { text: "Dos cosas llenan el ánimo de admiración: el cielo estrellado sobre mí y la ley moral dentro de mí.", author: "Immanuel Kant", source: "Crítica de la razón práctica, conclusión" },
  { text: "Atrévete a servirte de tu propio entendimiento. Sapere aude.", author: "Immanuel Kant", source: "Respuesta a la pregunta: ¿Qué es la Ilustración?" },
  { text: "El hombre es la medida de todas las cosas.", author: "Protágoras", source: "Platón, Teeteto, 152a" },
  { text: "No podemos bañarnos dos veces en el mismo río.", author: "Heráclito", source: "Fragmentos, DK 22 B 91" },
  { text: "El carácter del hombre es su destino.", author: "Heráclito", source: "Fragmentos, DK 22 B 119" },
  { text: "Soporta y abstente.", author: "Epicteto", source: "Fragmentos, 10" },
  { text: "La única cosa que sé es que no sé nada.", author: "Sócrates", source: "Platón, Apología, 21d" },
  { text: "Lo que perturba a los hombres no son las cosas, sino los juicios que sobre las cosas se forjan.", author: "Epicteto", source: "Enquiridión, 5" },
  { text: "Recuerda que no es un insulto lo que te ofende, sino tu propia opinión acerca del insulto.", author: "Epicteto", source: "Enquiridión, 20" },
  { text: "Si quieres progresar, renuncia a pensamientos como este: si descuido mis asuntos no tendré con qué vivir.", author: "Epicteto", source: "Enquiridión, 12" },
  { text: "En todo lo que te ocurra, recuerda recogerte en ti mismo y preguntarte qué facultad tienes para afrontarlo.", author: "Epicteto", source: "Enquiridión, 10" },
  { text: "Ninguna cosa hace tan grande al alma como poder examinar con método y verdad todas las cosas que se presentan en la vida.", author: "Marco Aurelio", source: "Meditaciones, III.11" },
  { text: "Al despertar por la mañana, di a ti mismo: hoy me encontraré con entrometidos, ingratos, soberbios, traidores, envidiosos.", author: "Marco Aurelio", source: "Meditaciones, II.1" },
  { text: "Acostúmbrate a prestar atención solo a lo que te está diciendo otro, y, en la medida de lo posible, métete en el alma del que habla.", author: "Marco Aurelio", source: "Meditaciones, VI.53" },
  { text: "Piensa en los muertos ilustres: todos tuvieron sus mismos deseos, sus mismos miedos, y ahora solo son polvo.", author: "Marco Aurelio", source: "Meditaciones, IV.33" },
  { text: "La mejor manera de vengarse de un enemigo es no parecerse a él.", author: "Marco Aurelio", source: "Meditaciones, VI.6" },
  { text: "Pronto habrás olvidado todo; pronto todos te habrán olvidado a ti.", author: "Marco Aurelio", source: "Meditaciones, VII.21" },
  { text: "Si te angustia una cosa externa, no es ella la que te inquieta, sino el juicio que tú haces sobre ella; y está en tu poder borrar ese juicio.", author: "Marco Aurelio", source: "Meditaciones, VIII.47" },
  { text: "El universo es cambio; la vida es opinión.", author: "Marco Aurelio", source: "Meditaciones, IV.3" },
  { text: "Borra la imaginación. Detén el tirón de la pasión. Circunscribe el momento presente.", author: "Marco Aurelio", source: "Meditaciones, VII.29" },
  { text: "No desdeñes la muerte, acéptala con buen ánimo, pues también ella es una de esas cosas que la naturaleza quiere.", author: "Marco Aurelio", source: "Meditaciones, IX.3" },
  { text: "Nadie puede hacerte daño sin tu consentimiento.", author: "Marco Aurelio", source: "Meditaciones, XI.13" },
  { text: "Limita siempre tu pensamiento a lo presente, y así no tendrás ocasión de afligirte.", author: "Marco Aurelio", source: "Meditaciones, VIII.36" },
  { text: "Todo lo que ocurre es tan corriente y conocido como la rosa en primavera y el fruto en verano.", author: "Marco Aurelio", source: "Meditaciones, IV.44" },
  { text: "No vale la pena vivir, sino vivir bien. Y vivir bien es vivir conforme a la virtud.", author: "Sócrates", source: "Platón, Critón, 48b" },
  { text: "Allí donde el miedo, allí la salvación.", author: "Séneca", source: "Cartas a Lucilio, 24" },
  { text: "No es pobre el que tiene poco, sino el que mucho desea.", author: "Séneca", source: "Cartas a Lucilio, 2" },
  { text: "Mientras esperamos a vivir, la vida pasa.", author: "Séneca", source: "Cartas a Lucilio, 1" },
  { text: "Toda vida, si sabes usarla, es larga.", author: "Séneca", source: "Sobre la brevedad de la vida, II" },
  { text: "Vivir es la cosa más rara del mundo. La mayoría de la gente solo existe, eso es todo.", author: "Oscar Wilde", source: "El alma del hombre bajo el socialismo" },
  { text: "Nunca consideres hecho nada que aún quede por hacer.", author: "Lucano", source: "Farsalia, II.657" },
  { text: "El hombre prudente pone diques a su deseo, sabiendo que el deseo es fuego que arde mientras hay leña.", author: "Séneca", source: "Cartas a Lucilio, 116" },
  { text: "Tanto vale la vida como el uso que hacemos de ella.", author: "Michel de Montaigne", source: "Ensayos, I.20" },
  { text: "La manera más simple de dominar a los hombres es mantenerlos entretenidos.", author: "Montesquieu", source: "El espíritu de las leyes" },
  { text: "Todo está lleno de signos, y sabio es el que de una cosa deduce otra.", author: "Plotino", source: "Enéadas, II.3.7" },
  { text: "La palabra convence, pero el ejemplo arrastra.", author: "Séneca", source: "Cartas a Lucilio, 6" },
  { text: "El tiempo descubre la verdad.", author: "Séneca", source: "Cartas a Lucilio, 79" },
  { text: "El que teme a la muerte nunca disfrutará de la vida.", author: "Séneca", source: "Cartas a Lucilio, 4" },
  { text: "Aprende a morir y habrás aprendido a vivir.", author: "Michel de Montaigne", source: "Ensayos, I.20" },
  { text: "La vida, si se la emplea bien, es larga.", author: "Séneca", source: "Sobre la brevedad de la vida, II" },
  { text: "No el que tiene pocos bienes, sino el que ansía más, es pobre.", author: "Séneca", source: "Cartas a Lucilio, 2" },
  { text: "En ninguna parte encontrarás un retiro más tranquilo que en tu propia alma.", author: "Marco Aurelio", source: "Meditaciones, IV.3" },
  { text: "Lo que no es útil para el enjambre, tampoco lo es para la abeja.", author: "Marco Aurelio", source: "Meditaciones, VI.54" },
  { text: "Haz cada acción como si fuera la última de tu vida.", author: "Marco Aurelio", source: "Meditaciones, II.5" },
  { text: "El hombre superior se exige a sí mismo; el hombre vulgar exige a los demás.", author: "Confucio", source: "Analectas, XV.21" },
  { text: "El hombre superior es modesto en su discurso, pero sobresale en su acción.", author: "Confucio", source: "Analectas, XIV.27" },
  { text: "Aprender sin pensar es inútil; pensar sin aprender es peligroso.", author: "Confucio", source: "Analectas, II.15" },
  { text: "No te preocupes de no ser conocido; preocúpate de merecer ser conocido.", author: "Confucio", source: "Analectas, IV.14" },
  { text: "Cuando veas a un hombre bueno, trata de imitarlo; cuando veas a un hombre malo, examínate a ti mismo.", author: "Confucio", source: "Analectas, IV.17" },
  { text: "El que se conoce a sí mismo es sabio; el que se conquista a sí mismo es fuerte.", author: "Lao Tzu", source: "Tao Te Ching, 33" },
  { text: "Quien sabe no habla; quien habla no sabe.", author: "Lao Tzu", source: "Tao Te Ching, 56" },
  { text: "Manejar un gran estado es como freír un pez pequeño.", author: "Lao Tzu", source: "Tao Te Ching, 60" },
  { text: "El árbol que apenas se puede abrazar brotó de un diminuto retoño. La torre de nueve pisos comenzó con un montón de tierra.", author: "Lao Tzu", source: "Tao Te Ching, 64" },
  { text: "Cuando desaparece el gran Tao, aparecen la benevolencia y la justicia.", author: "Lao Tzu", source: "Tao Te Ches, 18" },
  { text: "El agua es el elemento más débil, pero vence a la roca más dura.", author: "Lao Tzu", source: "Tao Te Ching, 78" },
  { text: "Quien vence a otros es fuerte, quien se vence a sí mismo es poderoso.", author: "Lao Tzu", source: "Tao Te Ching, 33" },
  { text: "Saber y no obrar es no saber.", author: "Wang Yangming", source: "Instrucciones para la vida práctica" },
  { text: "Todo el que vive, vive de la vida de la naturaleza; todo lo demás son palabras.", author: "Johann Wolfgang von Goethe", source: "Fausto, II" },
  { text: "Lo que sabes debes aplicarlo; lo que no sabes debes aprenderlo.", author: "Johann Wolfgang von Goethe", source: "Máximas y reflexiones" },
  { text: "Basta con dar un paso, aunque sea pequeño, en la dirección correcta.", author: "Johann Wolfgang von Goethe", source: "Máximas y reflexiones" },
  { text: "No se conoce aquello que no se ama.", author: "Johann Wolfgang von Goethe", source: "Máximas y reflexiones" },
  { text: "Divide el día, y te habrá parecido más larga la noche.", author: "Johann Wolfgang von Goethe", source: "Máximas y reflexiones" },
  { text: "El genio es paciencia.", author: "Isaac Newton", source: "atribuida, correspondencia" },
  { text: "Todo lo que vale la pena hacer, vale la pena hacerlo bien.", author: "Philip Stanhope", source: "Cartas a su hijo" },
  { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates", source: "Platón, Apología, 23b" },
  { text: "Quien no comete errores no suele hacer descubrimientos.", author: "Samuel Smiles", source: "Ayúdate a ti mismo" },
  { text: "Si puedes pasar una tarde perfecta, solo, contigo mismo, has alcanzado un gran logro.", author: "Ralph Waldo Emerson", source: "Confianza en uno mismo" },
  { text: "Confía en ti mismo: toda alma vibra con esa cuerda de hierro.", author: "Ralph Waldo Emerson", source: "Confianza en uno mismo" },
  { text: "Lo que yace detrás de nosotros y lo que yace delante son pequeñas cosas comparadas con lo que yace dentro de nosotros.", author: "Ralph Waldo Emerson", source: "Ensayos, primera serie" },
  { text: "Sé tú mismo; nadie más puede serlo.", author: "Ralph Waldo Emerson", source: "Diario, 1841" },
  { text: "La única persona que eres destinado a ser, es la persona que decides ser.", author: "Ralph Waldo Emerson", source: "Ensayos" },
  { text: "A cada uno lo bello le parece bello según la disposición de su alma.", author: "Ralph Waldo Emerson", source: "Ensayos, Arte" },
  { text: "Fui a los bosques porque quería vivir con intención, enfrentar solo los hechos esenciales de la vida.", author: "Henry David Thoreau", source: "Walden, II" },
  { text: "Si un hombre no lleva el paso de sus compañeros, tal vez sea porque escucha un tambor distinto.", author: "Henry David Thoreau", source: "Walden, XVIII" },
  { text: "La masa de los hombres lleva vidas de silenciosa desesperación.", author: "Henry David Thoreau", source: "Walden, I" },
  { text: "Simplifica, simplifica.", author: "Henry David Thoreau", source: "Walden, II" },
  { text: "El precio de cualquier cosa es la cantidad de vida que cambias por ella.", author: "Henry David Thoreau", source: "Walden, I" },
  { text: "Solo hemos de temer al propio miedo.", author: "Henry David Thoreau", source: "Diario, 1851" },
  { text: "No hay riqueza tan grande como la vida.", author: "John Ruskin", source: "Hasta este último" },
  { text: "Uno no puede pensar bien, amar bien, dormir bien, si no ha comido bien.", author: "Virginia Woolf", source: "Una habitación propia" },
  { text: "Solo mediante la repetición se vuelve la vida más profunda.", author: "Søren Kierkegaard", source: "La repetición" },
  { text: "La vida solo puede ser comprendida mirando hacia atrás, pero debe ser vivida mirando hacia adelante.", author: "Søren Kierkegaard", source: "Diarios, 1843" },
  { text: "La angustia es el vértigo de la libertad.", author: "Søren Kierkegaard", source: "El concepto de la angustia" },
  { text: "Atreverse es perder pie momentáneamente. No atreverse es perderse a sí mismo.", author: "Søren Kierkegaard", source: "O lo uno o lo otro" },
  { text: "Lo único que no se puede aprender a hacer por otro es morir por otro.", author: "Søren Kierkegaard", source: "Diarios" },
  { text: "La mayor de las desgracias es no saber sufrir.", author: "Fiódor Dostoyevski", source: "Crimen y castigo" },
  { text: "Cada uno es culpable de todo y ante todos.", author: "Fiódor Dostoyevski", source: "Los hermanos Karamazov, VI.2" },
  { text: "Si Dios no existe, todo está permitido.", author: "Fiódor Dostoyevski", source: "Los hermanos Karamazov, XI.9" },
  { text: "El hombre es un misterio. Hay que desentrañarlo, y si te pasas la vida desentrañándolo, no digas que has perdido el tiempo.", author: "Fiódor Dostoyevski", source: "Carta a su hermano Mijaíl, 1839" },
  { text: "Solo por medio del sufrimiento podemos conocer la verdadera alegría.", author: "Fiódor Dostoyevski", source: "Los hermanos Karamazov" },
  { text: "Amar a los hombres en general es fácil; lo difícil es amarlos individualmente.", author: "Fiódor Dostoyevski", source: "Los hermanos Karamazov, II.4" },
  { text: "Quien quiere hacer el bien a los demás, primero debe aprender a dominarse a sí mismo.", author: "Fiódor Dostoyevski", source: "Memorias del subsuelo" },
  { text: "La belleza salvará al mundo.", author: "Fiódor Dostoyevski", source: "El idiota, III.5" },
  { text: "Quien tiene fe no necesita pruebas.", author: "Fiódor Dostoyevski", source: "Los hermanos Karamazov" },
  { text: "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.", author: "Marcel Proust", source: "La prisionera" },
  { text: "Lo único que hace la vida tolerable es lo que hacemos por los demás.", author: "Lewis Carroll", source: "carta" },
  { text: "El hombre no es nada más que lo que él se hace.", author: "Jean-Paul Sartre", source: "El existencialismo es un humanismo" },
  { text: "El infierno son los otros.", author: "Jean-Paul Sartre", source: "A puerta cerrada" },
  { text: "Estamos condenados a ser libres.", author: "Jean-Paul Sartre", source: "El ser y la nada" },
  { text: "Solo hay un problema filosófico verdaderamente serio: el suicidio.", author: "Albert Camus", source: "El mito de Sísifo" },
  { text: "Hay que imaginar a Sísifo feliz.", author: "Albert Camus", source: "El mito de Sísifo" },
  { text: "En lo más profundo del invierno, finalmente aprendí que dentro de mí habitaba un verano invencible.", author: "Albert Camus", source: "El verano" },
  { text: "El único modo de lidiar con un mundo sin libertad es volverse tan absolutamente libre que la propia existencia sea un acto de rebeldía.", author: "Albert Camus", source: "El hombre rebelde" },
  { text: "Todo hombre muere; no todo hombre realmente vive.", author: "William Wallace", source: "atribuida, tradición escocesa" },
  { text: "Lo esencial es invisible a los ojos.", author: "Antoine de Saint-Exupéry", source: "El Principito, XXI" },
  { text: "Solo con el corazón se puede ver bien. Lo esencial es invisible a los ojos.", author: "Antoine de Saint-Exupéry", source: "El Principito, XXI" },
  { text: "Amar no es mirarse el uno al otro, sino mirar juntos en la misma dirección.", author: "Antoine de Saint-Exupéry", source: "Tierra de hombres" },
  { text: "Dios me conceda serenidad para aceptar lo que no puedo cambiar, valor para cambiar lo que puedo y sabiduría para discernir la diferencia.", author: "Reinhold Niebuhr", source: "Oración de la serenidad" },
  { text: "Dichoso es el hombre que encuentra la sabiduría.", author: "Proverbios", source: "Proverbios, 3.13" },
  { text: "El que gobierna su espíritu es más fuerte que el que conquista una ciudad.", author: "Proverbios", source: "Proverbios, 16.32" },
  { text: "Donde no hay visión, el pueblo perece.", author: "Proverbios", source: "Proverbios, 29.18" },
  { text: "Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", author: "Eclesiastés", source: "Eclesiastés, 3.1" },
  { text: "No hay nada nuevo bajo el sol.", author: "Eclesiastés", source: "Eclesiastés, 1.9" },
  { text: "Vanidad de vanidades, todo es vanidad.", author: "Eclesiastés", source: "Eclesiastés, 1.2" },
  { text: "Al que persevera hasta el fin, ese se salvará.", author: "Jesús de Nazaret", source: "Mateo, 24.13" },
  { text: "No te inquietes por el mañana, pues el mañana traerá su propio afán.", author: "Jesús de Nazaret", source: "Mateo, 6.34" },
  { text: "Amarás a tu prójimo como a ti mismo.", author: "Jesús de Nazaret", source: "Mateo, 22.39" },
  { text: "Quien se exalta será humillado, y quien se humilla será exaltado.", author: "Jesús de Nazaret", source: "Lucas, 14.11" },
  { text: "El reino de Dios está dentro de vosotros.", author: "Jesús de Nazaret", source: "Lucas, 17.21" },
  { text: "Conoceréis la verdad, y la verdad os hará libres.", author: "Jesús de Nazaret", source: "Juan, 8.32" },
  { text: "Piensa como piensan los sabios, pero habla como habla la gente sencilla.", author: "Aristóteles", source: "atribuida" },
  { text: "Somos lo que hacemos repetidamente. La excelencia, pues, no es un acto, sino un hábito.", author: "Will Durant", source: "La historia de la filosofía (parafraseando a Aristóteles)" },
  { text: "La virtud es un hábito, una disposición permanente de la voluntad para lo honesto.", author: "Aristóteles", source: "Ética a Nicómaco, II.6" },
  { text: "La felicidad consiste en una actividad virtuosa del alma.", author: "Aristóteles", source: "Ética a Nicómaco, I.7" },
  { text: "Educar la mente sin educar el corazón no es educar en absoluto.", author: "Aristóteles", source: "atribuida, Ética a Nicómaco" },
  { text: "El hombre es por naturaleza un animal político.", author: "Aristóteles", source: "Política, I.2" },
  { text: "La amistad es un alma que habita en dos cuerpos.", author: "Aristóteles", source: "Diógenes Laercio, Vidas de filósofos, V.20" },
  { text: "Dudar de todo o creerlo todo son dos soluciones igualmente cómodas, pues ambas dispensan de reflexionar.", author: "Henri Poincaré", source: "La ciencia y la hipótesis" },
  { text: "Lo que no se mide no se puede mejorar.", author: "Lord Kelvin", source: "Conferencia, 1883" },
  { text: "La ciencia es el gran antídoto contra el veneno del entusiasmo y la superstición.", author: "Adam Smith", source: "La riqueza de las naciones, V.1" },
  { text: "La vida no examinada no merece ser vivida.", author: "Sócrates", source: "Platón, Apología, 38a" },
  { text: "El hombre llega a ser lo que piensa todo el día.", author: "Ralph Waldo Emerson", source: "Diario, 1845" },
  { text: "El entusiasmo es la vida del alma.", author: "Ralph Waldo Emerson", source: "Circles" },
  { text: "Nada grande se ha conseguido jamás sin entusiasmo.", author: "Ralph Waldo Emerson", source: "Ensayos, segunda serie" },
  { text: "Lo que hacemos por nosotros mismos muere con nosotros; lo que hacemos por los demás y por el mundo permanece y es inmortal.", author: "Albert Pike", source: "Morals and Dogma" },
  { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali", source: "entrevista, 1977" },
  { text: "La disciplina es el puente entre metas y logros.", author: "Jim Rohn", source: "conferencias, The Art of Exceptional Living" },
  { text: "No deseo que las cosas sean más fáciles; deseo ser mejor.", author: "Jim Rohn", source: "conferencias" },
  { text: "Todos los problemas del hombre derivan de su incapacidad para permanecer quieto a solas en una habitación.", author: "Blaise Pascal", source: "Pensamientos, 139" },
  { text: "El corazón tiene razones que la razón no conoce.", author: "Blaise Pascal", source: "Pensamientos, 277" },
  { text: "El hombre es una caña pensante, la más débil de la naturaleza, pero una caña pensante.", author: "Blaise Pascal", source: "Pensamientos, 347" },
  { text: "Grandeza y miseria del hombre: lo son a tal punto que la verdad se las prueba una a otra.", author: "Blaise Pascal", source: "Pensamientos, 416" },
  { text: "El silencio eterno de los espacios infinitos me espanta.", author: "Blaise Pascal", source: "Pensamientos, 206" },
  { text: "Pensamos poco en el presente; si pensamos en él, es únicamente para tomar luz con qué ordenar el porvenir.", author: "Blaise Pascal", source: "Pensamientos, 172" },
  { text: "Quien se envanece de la gloria posee menos gloria de la que cree.", author: "Baltasar Gracián", source: "Oráculo manual, 168" },
  { text: "Más vale ser desgraciado con un amigo que feliz sin él.", author: "Baltasar Gracián", source: "Oráculo manual, 158" },
  { text: "Lo bueno, si breve, dos veces bueno.", author: "Baltasar Gracián", source: "Oráculo manual, 105" },
  { text: "Saber y no saberlo mostrar es dos veces no saber.", author: "Baltasar Gracián", source: "Oráculo manual, 148" },
  { text: "Hay que hablar como con el testamento, que con menos palabras, menos pleitos.", author: "Baltasar Gracián", source: "Oráculo manual" },
  { text: "Quien tiene el porqué para vivir puede soportar casi cualquier cómo.", author: "Viktor Frankl", source: "El hombre en busca de sentido, I" },
  { text: "Entre estímulo y respuesta hay un espacio. En ese espacio está nuestro poder para elegir nuestra respuesta.", author: "Viktor Frankl", source: "El hombre en busca de sentido" },
  { text: "Todo le puede ser arrebatado al hombre, excepto una cosa: la última de las libertades humanas, la elección de actitud ante cualquier circunstancia.", author: "Viktor Frankl", source: "El hombre en busca de sentido, I" },
  { text: "El sentido de la vida es dar sentido a la vida.", author: "Viktor Frankl", source: "La voluntad de sentido" },
  { text: "Cuando ya no podemos cambiar la situación, nos enfrentamos al desafío de cambiarnos a nosotros mismos.", author: "Viktor Frankl", source: "El hombre en busca de sentido" },
  { text: "El éxito, como la felicidad, no puede perseguirse; debe sobrevenir como consecuencia de la entrega personal.", author: "Viktor Frankl", source: "El hombre en busca de sentido, prefacio" },
  { text: "Vive como si fueras a vivir por segunda vez y como si la primera vez hubieras obrado tan desacertadamente como ahora estás a punto de obrar.", author: "Viktor Frankl", source: "El hombre en busca de sentido, II" },
  { text: "Un hombre debe tener una razón para vivir. No basta con estar vivo.", author: "Viktor Frankl", source: "La voluntad de sentido" },
  { text: "No hay nada tan intolerable para el hombre como estar en pleno reposo, sin pasiones, sin ocupación, sin diversión, sin estudio.", author: "Blaise Pascal", source: "Pensamientos, 131" },
  { text: "El que busca la verdad corre el riesgo de encontrarla.", author: "Isabel Allende", source: "La casa de los espíritus" },
  { text: "Quien se conoce a sí mismo conoce su Señor.", author: "Rumi", source: "Masnavi, I" },
  { text: "Ayer era inteligente, por eso quería cambiar el mundo. Hoy soy sabio, por eso me estoy cambiando a mí mismo.", author: "Rumi", source: "atribuida, tradición sufí" },
  { text: "La herida es el lugar por donde entra la luz en ti.", author: "Rumi", source: "Diván de Shams, 1372" },
  { text: "Si todo lo que tienes es un martillo, todo te parecerá un clavo.", author: "Abraham Maslow", source: "La psicología de la ciencia" },
  { text: "Lo que un hombre puede ser, debe serlo. A esta necesidad la llamamos autorrealización.", author: "Abraham Maslow", source: "Motivación y personalidad" },
  { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi", source: "atribuida, escritos completos" },
  { text: "La fuerza no proviene de la capacidad física, sino de una voluntad indomable.", author: "Mahatma Gandhi", source: "discurso" },
  { text: "Vive como si fueras a morir mañana; aprende como si fueras a vivir para siempre.", author: "Mahatma Gandhi", source: "Young India, 1925" },
  { text: "No me preguntes qué ha hecho mi país por mí, pregunta qué he hecho yo por mi país.", author: "John F. Kennedy", source: "Discurso inaugural, 1961" },
  { text: "Lo que importa no es lo que te ocurre, sino cómo reaccionas a ello.", author: "Epicteto", source: "Enquiridión, 5" },
  { text: "Primero dite a ti mismo qué quieres ser; y luego haz lo que tienes que hacer.", author: "Epicteto", source: "Enquiridión, 29" },
  { text: "La dificultad muestra lo que son los hombres.", author: "Epicteto", source: "Enquiridión, 17" },
  { text: "No trates que las cosas ocurran como tú quieres; desea que las cosas ocurran como ocurren, y tu vida transcurrirá con serenidad.", author: "Epicteto", source: "Enquiridión, 8" },
  { text: "Recuerda actuar en la vida como si estuvieras en un banquete: coge la parte que pase cerca de ti con modestia.", author: "Epicteto", source: "Enquiridión, 15" },
  { text: "Si quieres progresar, abandona los razonamientos como: si descuido mis asuntos no tendré con qué vivir.", author: "Epicteto", source: "Enquiridión, 12" },
  { text: "Cuando alguien te ofenda, piensa que él cree estar obligado a obrar como obra. Es imposible que actúe según tu parecer.", author: "Epicteto", source: "Enquiridión, 42" },
  { text: "No pidas que suceda lo que quieres, sino quiere lo que sucede, y serás feliz.", author: "Epicteto", source: "Enquiridión, 8" },
  { text: "La gente no queda turbada por lo que ocurre, sino por los juicios que hacen de ello.", author: "Epicteto", source: "Enquiridión, 5" },
  { text: "Primero sé tú lo que quieres ser, luego haz lo que tengas que hacer.", author: "Epicteto", source: "Discursos, III.23" },
  { text: "Un día, si pones atención, vencerás a cada deseo.", author: "Epicteto", source: "Discursos, II.18" },
  { text: "Si alguien confiara tu cuerpo al primero que pasase, te enojarías. ¿Y no te avergüenzas de confiar tu alma al primero que pasa?", author: "Epicteto", source: "Discursos, II.6" },
  { text: "Si quieres ser bueno, empieza por creer que eres malo.", author: "Epicteto", source: "Discursos, IV.6" },
  { text: "La libertad no se consigue satisfaciendo los propios deseos, sino suprimiéndolos.", author: "Epicteto", source: "Discursos, IV.1" },
  { text: "Es imposible que un hombre aprenda lo que cree ya saber.", author: "Epicteto", source: "Discursos, II.17" },
  { text: "No eres más valioso por tener un cuerpo hermoso, sino por tener una mente hermosa.", author: "Epicteto", source: "Discursos, IV.1" },
  { text: "Un hombre libre no se queja de nadie, no se queja de sí mismo.", author: "Epicteto", source: "Enquiridión, 48" },
  { text: "Si no puedes ser cabeza de león, sé cola de león.", author: "Epicteto", source: "Discursos, III.22" },
  { text: "Al hombre lo domina lo que lo domina; y lo que lo domina es lo que él cree que lo domina.", author: "Epicteto", source: "Discursos, III.24" },
  { text: "No existe lo feo, lo malo, lo triste más que para el hombre que los admite.", author: "Séneca", source: "Sobre la providencia" },
  { text: "Mientras vivimos, mientras estamos entre los hombres, cultivemos la humanidad.", author: "Séneca", source: "Sobre la ira, III.43" },
  { text: "Errar es humano, pero perseverar en el error solo del necio.", author: "Séneca", source: "Cartas a Lucilio, 71" },
  { text: "Nadie desea lo ajeno porque le guste tener mucho, sino porque posee poco.", author: "Séneca", source: "Cartas a Lucilio, 74" },
  { text: "Dondequiera que haya un ser humano, hay oportunidad para un acto de bondad.", author: "Séneca", source: "Sobre la vida feliz" },
  { text: "Toda crueldad brota de la flaqueza.", author: "Séneca", source: "Sobre la clemencia" },
  { text: "La suerte no existe. Existe el momento en que el talento se encuentra con la oportunidad.", author: "Séneca", source: "Cartas a Lucilio, 18 (paráfrasis tradicional)" },
  { text: "La virtud no quiere ser celebrada con grandes voces, sino aceptada en silencio.", author: "Séneca", source: "Cartas a Lucilio, 79" },
  { text: "Los vicios nos prometen placer, pero nos imponen esclavitud.", author: "Séneca", source: "Cartas a Lucilio, 39" },
  { text: "No hay viento favorable para quien no sabe a dónde va.", author: "Séneca", source: "Cartas a Lucilio, 71" },
  { text: "Toda persona nueva es un nuevo comienzo del mundo.", author: "Hannah Arendt", source: "La condición humana" },
  { text: "La tradición del trabajo manual ha convertido al hombre en siervo de sus propias herramientas.", author: "Hannah Arendt", source: "La condición humana" },
  { text: "Nadie tiene el derecho de obedecer.", author: "Hannah Arendt", source: "Responsabilidad y juicio" },
  { text: "La atención, tomada en su grado más alto, es la misma cosa que la oración.", author: "Simone Weil", source: "La gravedad y la gracia" },
  { text: "La belleza está eternamente presente en todas las cosas, pero se oculta a los que no la buscan.", author: "Simone Weil", source: "Cuadernos" },
  { text: "El mal que obra en nosotros lo proyectamos en torno nuestro.", author: "Simone Weil", source: "La gravedad y la gracia" },
  { text: "El esclavo es aquel a quien no se entrega ningún fin en cuyo nombre pueda padecer.", author: "Simone Weil", source: "La condición obrera" },
  { text: "Los límites del lenguaje son los límites de mi mundo.", author: "Ludwig Wittgenstein", source: "Tractatus Logico-Philosophicus, 5.6" },
  { text: "De lo que no se puede hablar, hay que callar.", author: "Ludwig Wittgenstein", source: "Tractatus Logico-Philosophicus, 7" },
  { text: "La muerte no es un acontecimiento de la vida. No se vive la muerte.", author: "Ludwig Wittgenstein", source: "Tractatus Logico-Philosophicus, 6.4311" },
  { text: "Si un león pudiera hablar, no podríamos entenderlo.", author: "Ludwig Wittgenstein", source: "Investigaciones filosóficas, II.xi" },
  { text: "Una expresión solo tiene significado en el flujo de la vida.", author: "Ludwig Wittgenstein", source: "Observaciones sobre la filosofía de la psicología" },
  { text: "Quien hace sus cuentas cada día no será sorprendido por la muerte.", author: "Michel de Montaigne", source: "Ensayos, I.20" },
  { text: "No corregimos al que ahorcamos; corregimos a los otros por él.", author: "Michel de Montaigne", source: "Ensayos, III.8" },
  { text: "La grandeza del alma no está tanto en subir alto, como en saber ordenarse.", author: "Michel de Montaigne", source: "Ensayos, III.13" },
  { text: "Lo mejor es moderarnos en el goce, y recibir lo malo con valor.", author: "Michel de Montaigne", source: "Ensayos, I.39" },
  { text: "Los que han comparado nuestra vida a un sueño tenían, quizás, más razón de la que creían.", author: "Michel de Montaigne", source: "Ensayos, II.12" },
  { text: "Nadie es libre si no es dueño de sí mismo.", author: "Epicteto", source: "Fragmentos, 36" },
  { text: "Debemos acostumbrarnos a que la felicidad no está en las cosas, sino en el uso que hagamos de ellas.", author: "Séneca", source: "Cartas a Lucilio, 9" },
  { text: "El sabio nunca se asombra de nada. Nihil admirari.", author: "Horacio", source: "Epístolas, I.6" },
  { text: "Atrévete a ser sabio; empieza.", author: "Horacio", source: "Epístolas, I.2" },
  { text: "Carpe diem, disfruta del día, fíate lo menos posible del mañana.", author: "Horacio", source: "Odas, I.11" },
  { text: "Gota a gota el agua ablanda la piedra.", author: "Ovidio", source: "Cartas desde el Ponto, IV.10" },
  { text: "La fortuna favorece a los audaces.", author: "Virgilio", source: "Eneida, X.284" },
  { text: "Pueden porque creen poder.", author: "Virgilio", source: "Eneida, V.231" },
  { text: "Del dicho al hecho hay mucho trecho.", author: "Miguel de Cervantes", source: "Don Quijote, II.34" },
  { text: "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.", author: "Miguel de Cervantes", source: "Don Quijote, II.58" },
  { text: "Yo sé quién soy, y sé que puedo ser no solo los que he dicho, sino todos los Doce Pares de Francia.", author: "Miguel de Cervantes", source: "Don Quijote, I.5" },
  { text: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", author: "Miguel de Cervantes", source: "Don Quijote, II.25" },
  { text: "La mejor salsa del mundo es el hambre.", author: "Miguel de Cervantes", source: "Don Quijote, II.5" },
  { text: "Dime con quién andas y te diré quién eres.", author: "Miguel de Cervantes", source: "Don Quijote, II.10" },
  { text: "Hay hombres que luchan un día y son buenos. Hay otros que luchan un año y son mejores. Hay quienes luchan muchos años y son muy buenos. Pero hay los que luchan toda la vida: esos son los imprescindibles.", author: "Bertolt Brecht", source: "Loa a la dialéctica" },
  { text: "Primero vinieron por los comunistas, y yo no hablé porque no era comunista.", author: "Martin Niemöller", source: "Primero vinieron" },
  { text: "Aquel que tiene un amigo, tiene un tesoro.", author: "Séneca", source: "Cartas a Lucilio, 3 (paráfrasis)" },
  { text: "No es feliz el que no cree serlo.", author: "Publilio Siro", source: "Sentencias" },
  { text: "Incluso la piedra más dura se desgasta con el continuo caer de las gotas.", author: "Lucrecio", source: "De rerum natura, I.313" },
  { text: "Nada surge de la nada.", author: "Lucrecio", source: "De rerum natura, I.150" },
  { text: "La religión ha podido persuadir a los hombres de muchas maldades.", author: "Lucrecio", source: "De rerum natura, I.101" },
  { text: "La felicidad no es un destino al que se llega, sino una manera de viajar.", author: "Margaret Lee Runbeck", source: "Time for Each Other" },
  { text: "El que ama, obedece.", author: "Miguel de Unamuno", source: "Del sentimiento trágico de la vida, IX" },
  { text: "Solo el que sabe es libre, y más libre el que más sabe.", author: "Miguel de Unamuno", source: "Del sentimiento trágico de la vida" },
  { text: "Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.", author: "José Ortega y Gasset", source: "Meditaciones del Quijote" },
  { text: "La vida nos es dada, pero no nos es dada hecha.", author: "José Ortega y Gasset", source: "Historia como sistema" },
  { text: "Vivir es, esencialmente, estar decidiendo lo que vamos a ser.", author: "José Ortega y Gasset", source: "¿Qué es filosofía?" },
  { text: "Solo es posible avanzar cuando se mira lejos.", author: "José Ortega y Gasset", source: "La rebelión de las masas" },
  { text: "El esfuerzo inútil conduce a la melancolía.", author: "José Ortega y Gasset", source: "La deshumanización del arte" },
  { text: "El hombre superior es sereno.", author: "Confucio", source: "Analectas, VII.36" },
  { text: "Cuando sepas algo, mantén que lo sabes; y cuando no sepas una cosa, permite que no la sabes.", author: "Confucio", source: "Analectas, II.17" },
  { text: "El que se venga debe cavar dos tumbas.", author: "Confucio", source: "atribuida, Analectas" },
  { text: "Estudiar sin reflexionar es malgastar el tiempo; reflexionar sin estudiar es peligroso.", author: "Confucio", source: "Analectas, II.15" },
  { text: "Cuando enojado, piensa en las consecuencias.", author: "Confucio", source: "Analectas, XVI.10" },
  { text: "La piedra preciosa no puede pulirse sin fricción, ni el hombre perfeccionarse sin pruebas.", author: "Confucio", source: "Analectas" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau", source: "Emilio, II" },
  { text: "El hombre ha nacido libre, y en todas partes se halla encadenado.", author: "Jean-Jacques Rousseau", source: "El contrato social, I.1" },
  { text: "Renunciar a la libertad es renunciar a la cualidad de hombre, a los derechos de la humanidad.", author: "Jean-Jacques Rousseau", source: "El contrato social, I.4" },
  { text: "El dinero que se posee es instrumento de libertad; el que se persigue lo es de servidumbre.", author: "Jean-Jacques Rousseau", source: "Confesiones" },
  { text: "La verdadera felicidad no se compone sino de poco ruido y muchas estrellas.", author: "Jean-Jacques Rousseau", source: "Las ensoñaciones del paseante solitario" },
  { text: "El amor es un océano sin orilla ni fondo.", author: "Jalâl-ud-Din Rumi", source: "Masnavi, V" },
  { text: "Sois un ala en vuelo, no la jaula donde caéis.", author: "Jalâl-ud-Din Rumi", source: "Diván de Shams" },
  { text: "Silencia tu lengua si quieres oír al corazón.", author: "Jalâl-ud-Din Rumi", source: "Masnavi" },
  { text: "Lo que buscas también te está buscando.", author: "Jalâl-ud-Din Rumi", source: "Diván de Shams" },
  { text: "Ayer era listo, por eso quería cambiar el mundo; hoy soy sabio, por eso me cambio a mí mismo.", author: "Jalâl-ud-Din Rumi", source: "Masnavi (atribuida)" },
  { text: "No te aflijas. Lo que pierdes vuelve en otra forma.", author: "Jalâl-ud-Din Rumi", source: "Masnavi, II" },
  { text: "Eres un volumen del universo. No es un error. Eres el universo entero en un movimiento de éxtasis.", author: "Jalâl-ud-Din Rumi", source: "Masnavi, III" },
  { text: "En el silencio de la noche, mi corazón late por ti.", author: "Jalâl-ud-Din Rumi", source: "Diván de Shams" },
  { text: "Levanta tus palabras, no tu voz. Es la lluvia la que hace crecer las flores, no el trueno.", author: "Jalâl-ud-Din Rumi", source: "atribuida, tradición sufí" },
  { text: "No se aprende a vivir: se vive.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra, I" },
  { text: "Aquel que tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche", source: "El ocaso de los ídolos" },
  { text: "Lo que no me mata me hace más fuerte.", author: "Friedrich Nietzsche", source: "El crepúsculo de los ídolos, Máximas, 8" },
  { text: "Quien lucha contra monstruos debe cuidarse de no convertirse él mismo en monstruo.", author: "Friedrich Nietzsche", source: "Más allá del bien y del mal, 146" },
  { text: "Si miras largamente al abismo, el abismo también mira dentro de ti.", author: "Friedrich Nietzsche", source: "Más allá del bien y del mal, 146" },
  { text: "Sin música la vida sería un error.", author: "Friedrich Nietzsche", source: "El crepúsculo de los ídolos, Máximas, 33" },
  { text: "Ámate a ti mismo con la fidelidad que amarías a un amigo.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra" },
  { text: "El hombre es algo que debe ser superado. ¿Qué habéis hecho para superarlo?", author: "Friedrich Nietzsche", source: "Así habló Zaratustra, prólogo" },
  { text: "Uno debe tener caos dentro de sí para poder dar a luz una estrella danzante.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra, prólogo, 5" },
  { text: "No son nuestras opiniones, sino nuestro temperamento, lo que nos hace lo que somos.", author: "Friedrich Nietzsche", source: "Humano, demasiado humano" },
  { text: "El fruto más maduro de la injusticia es un alma libre.", author: "Friedrich Nietzsche", source: "Aurora, 379" },
  { text: "La verdadera gratitud es la memoria del corazón.", author: "Friedrich Nietzsche", source: "Aurora" },
  { text: "Cuando uno no encuentra la grandeza en Dios, no la encuentra en ninguna parte; hay que negarla o crearla.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra" },
  { text: "No hay hechos, solo interpretaciones.", author: "Friedrich Nietzsche", source: "La voluntad de poder, 481" },
  { text: "La madurez del hombre es haber recobrado la seriedad que tenía cuando era niño, al jugar.", author: "Friedrich Nietzsche", source: "Más allá del bien y del mal, 94" },
  { text: "Vive peligrosamente. Construye tus ciudades en las laderas del Vesubio.", author: "Friedrich Nietzsche", source: "La gaya ciencia, 283" },
  { text: "Este es mi camino, ¿cuál es el tuyo? El camino, no existe.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra, III" },
  { text: "Amo al que vive para conocer, y que quiere conocer para que viva un día el superhombre.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra, prólogo, 4" },
  { text: "Quien quiera aprender a volar, primero debe aprender a pararse, a caminar, a correr, a escalar y a bailar.", author: "Friedrich Nietzsche", source: "Así habló Zaratustra, III" },
  { text: "La vida consiste en reírse, incluso de nuestras propias lágrimas.", author: "Friedrich Nietzsche", source: "Más allá del bien y del mal" },
  { text: "Ser grande es dar dirección. Ningún río es grande y abundante por sí mismo: es que recibe y lleva consigo muchos afluentes.", author: "Friedrich Nietzsche", source: "Aurora, 168" },
  { text: "La riqueza más segura es la pobreza de las necesidades.", author: "Séneca", source: "Cartas a Lucilio, 17" },
  { text: "Cada uno es el artífice de su propia fortuna.", author: "Apio Claudio Ciego", source: "Sallust, Ad Caesarem, I.1" },
  { text: "Recuerda que no puedes aprender aquello que crees ya saber.", author: "Epicteto", source: "Discursos, II.17" },
  { text: "En todas las cosas, el hombre sabio considera primero el fin.", author: "Esopo", source: "Fábulas" },
  { text: "Lento pero seguro, se gana la carrera.", author: "Esopo", source: "La liebre y la tortuga" },
  { text: "La unión hace la fuerza.", author: "Esopo", source: "Fábulas" },
  { text: "Cualquier acto de bondad, por pequeño que sea, no se desperdicia.", author: "Esopo", source: "Fábulas" },
  { text: "Aquel que es discreto es mirado por los dioses.", author: "Esopo", source: "Fábulas" },
  { text: "No seas esclavo de tu propia pasión. Apasionarse por la serenidad, eso es virtud.", author: "Séneca", source: "Sobre la ira, III.36" },
  { text: "Examinar la jornada al término de cada día: este era el consejo que Sextio se daba a sí mismo.", author: "Séneca", source: "Sobre la ira, III.36" },
  { text: "El que no se toma trabajo por los amigos no puede esperar que los amigos se lo tomen por él.", author: "Séneca", source: "Cartas a Lucilio, 9" },
  { text: "No es poco el trabajo de forjarse a sí mismo un hombre interior.", author: "Séneca", source: "Cartas a Lucilio, 41" },
  { text: "Nada hay tan engañoso como la vida humana.", author: "Séneca", source: "Sobre la brevedad de la vida, X" },
  { text: "Mientras vivas, aprende a vivir.", author: "Séneca", source: "Sobre la brevedad de la vida, VII" },
  { text: "Retírate dentro de ti mismo en lo posible. Trata con los que puedan hacerte mejor.", author: "Séneca", source: "Cartas a Lucilio, 7" },
  { text: "Calma el alma leyendo: los libros son las medicinas del alma.", author: "Diodoro Sículo", source: "Biblioteca histórica, I.49" },
  { text: "Los libros son las abejas que llevan el polen de una inteligencia a otra.", author: "James Russell Lowell", source: "Conversaciones con antiguos poetas" },
  { text: "Siempre imaginé el Paraíso como una especie de biblioteca.", author: "Jorge Luis Borges", source: "Poema de los dones" },
  { text: "Uno no es lo que es por lo que escribe, sino por lo que ha leído.", author: "Jorge Luis Borges", source: "entrevista, 1980" },
  { text: "El olvido, no la memoria, es la condición de nuestra lucidez.", author: "Jorge Luis Borges", source: "Funes el memorioso" },
  { text: "Un libro es más que una estructura verbal; es el diálogo que entabla con su lector.", author: "Jorge Luis Borges", source: "Prólogos, con un prólogo de prólogos" },
  { text: "El arte ocurre cada vez que leemos un poema.", author: "Jorge Luis Borges", source: "Arte poética" },
  { text: "Que otros se jacten de las páginas que han escrito; a mí me enorgullecen las que he leído.", author: "Jorge Luis Borges", source: "Un lector" },
  { text: "Hombres necios que acusáis a la mujer sin razón, sin ver que sois la ocasión de lo mismo que culpáis.", author: "Sor Juana Inés de la Cruz", source: "Redondillas" },
  { text: "No estudio para saber más, sino para ignorar menos.", author: "Sor Juana Inés de la Cruz", source: "Respuesta a Sor Filotea" },
  { text: "Lo que no ocurra este año, ocurrirá al siguiente.", author: "Proverbio español", source: "tradición popular" },
  { text: "No se pierde el que sabe perder.", author: "Proverbio español", source: "tradición popular" },
  { text: "Más vale tarde que nunca.", author: "Tito Livio", source: "Ab urbe condita, IV.2" },
  { text: "No se debe hablar mal de los muertos.", author: "Quilón de Esparta", source: "Diógenes Laercio, Vidas, I.70" },
  { text: "El tiempo es lo más valioso que puede gastar un hombre.", author: "Teofrasto", source: "Diógenes Laercio, Vidas, V.40" },
  { text: "Si te duele todavía, es que aún no lo has soltado.", author: "Buda", source: "atribuida, tradición zen" },
  { text: "El dolor es inevitable; el sufrimiento es opcional.", author: "Buda", source: "atribuida, tradición budista" },
  { text: "Tres cosas no pueden ocultarse por mucho tiempo: el sol, la luna y la verdad.", author: "Buda", source: "atribuida, tradición budista" },
  { text: "Si encuentras sabio a un hombre que te muestre tus faltas, sigue a tal hombre como sigues a un tesoro.", author: "Buda", source: "Dhammapada, VI.76" },
  { text: "El hombre vano es fácil de descubrir; el hombre modesto es difícil de hallar.", author: "Buda", source: "Dhammapada, XVIII.252" },
  { text: "Todo lo que somos es resultado de lo que hemos pensado: está fundado en nuestros pensamientos.", author: "Buda", source: "Dhammapada, I.1" },
  { text: "No busques refugio en los demás; sé tu propia luz.", author: "Buda", source: "Mahaparinirvana Sutra, II.26" },
  { text: "Como la lluvia penetra en una casa mal techada, así la pasión penetra en una mente no cultivada.", author: "Buda", source: "Dhammapada, I.13" },
  { text: "Aunque uno conquiste mil veces a mil hombres en batalla, quien se conquista a sí mismo es el mayor conquistador.", author: "Buda", source: "Dhammapada, VIII.103" },
  { text: "Odiar es como beber veneno y esperar que muera el otro.", author: "Buda", source: "atribuida, tradición budista" },
  { text: "La mente lo es todo. Lo que piensas, te conviertes en ello.", author: "Buda", source: "atribuida, Dhammapada" },
  { text: "Elige a tus amigos con cuidado; los que amamos determinan lo que somos.", author: "Buda", source: "atribuida, tradición budista" },
  { text: "El mundo se sostiene sobre cuatro cosas: la sabiduría del sabio, la justicia del grande, las plegarias del piadoso y el valor del valiente.", author: "Mahoma", source: "Hadices" },
  { text: "El mayor yihad es el combate contra uno mismo.", author: "Mahoma", source: "Hadices" },
  { text: "La paciencia es la llave del alivio.", author: "Mahoma", source: "Hadices" },
  { text: "Ser lo que somos, y llegar a ser lo que somos capaces de ser, es el único fin de la vida.", author: "Robert Louis Stevenson", source: "Familiar Studies of Men and Books" },
  { text: "Juzga cada día no por la cosecha que recoges, sino por las semillas que plantas.", author: "Robert Louis Stevenson", source: "atribuida" },
  { text: "El joven cree que su obligación primera es con los demás; el anciano sabe que es con él mismo.", author: "Robert Louis Stevenson", source: "Virginibus Puerisque" },
  { text: "Lo que ganamos con demasiada facilidad, lo estimamos demasiado poco.", author: "Thomas Paine", source: "La crisis americana, I" },
  { text: "Aquellos que esperan recoger las bendiciones de la libertad deben, como los hombres, soportar la fatiga de sostenerla.", author: "Thomas Paine", source: "La crisis americana, I" },
  { text: "La libertad no es más que el reconocimiento de la necesidad.", author: "Friedrich Engels", source: "Anti-Dühring, I.XI" },
  { text: "Los filósofos se han limitado a interpretar el mundo de distintos modos; de lo que se trata es de transformarlo.", author: "Karl Marx", source: "Tesis sobre Feuerbach, XI" },
  { text: "La historia se repite: primero como tragedia y luego como farsa.", author: "Karl Marx", source: "El 18 Brumario de Luis Bonaparte" },
  { text: "La religión es el suspiro de la criatura oprimida, el corazón de un mundo sin corazón.", author: "Karl Marx", source: "Crítica de la filosofía del derecho de Hegel" },
  { text: "Lo esencial no es lo que el hombre cree, sino lo que hace.", author: "Miguel de Unamuno", source: "La agonía del cristianismo" },
  { text: "Se puede resistir a la invasión de un ejército; pero no se puede resistir a la invasión de las ideas.", author: "Victor Hugo", source: "Historia de un crimen, V.10" },
  { text: "Cuarenta años es la vejez de la juventud, cincuenta es la juventud de la vejez.", author: "Victor Hugo", source: "Los miserables" },
  { text: "La forma de la ciudad cambia más deprisa, ay, que el corazón de un mortal.", author: "Charles Baudelaire", source: "El cisne, Las flores del mal" },
  { text: "Siempre hay que estar ebrio. Todo está ahí: es la única cuestión.", author: "Charles Baudelaire", source: "El esplín de París, XXXIII" },
  { text: "La lectura es a la mente lo que el ejercicio al cuerpo.", author: "Joseph Addison", source: "The Tatler" },
  { text: "Lo peor que podemos decir de un hombre es que no lee.", author: "Joseph Addison", source: "The Spectator" },
  { text: "El sentimiento más fuerte y duradero del hombre es el miedo, y por encima de todo, el miedo a lo desconocido.", author: "H.P. Lovecraft", source: "El horror sobrenatural en la literatura" },
  { text: "Una copa de vino llena es una respuesta elocuente a mil preguntas.", author: "Proverbio japonés", source: "tradición popular" },
  { text: "Cae siete veces, levántate ocho.", author: "Proverbio japonés", source: "tradición popular" },
];
