/**
 * 365 frases sobre consciencia, poder elevado y manifestación.
 * Una por día del año. Rotan determinísticamente.
 *
 * Esta es la "carta al universo" diaria: aparece en la pantalla
 * de meditación como una reflexión recibida, no escrita. Estilo
 * horóscopo pero con densidad estoica-dispenza-hill.
 *
 * Cobertura: presencia · ego como observador · coherencia
 *            corazón-cerebro · manifestación (Hill / Dispenza) ·
 *            gratitud anticipada · identidad vs persona · el campo
 *            cuántico del observador · rendición activa · intención
 *            clara · romper el hábito de ser uno mismo · el yo
 *            futuro · autosugestión · energía elevada · vibración ·
 *            silencio · el sexto sentido · subconsciente.
 *
 * Tono: elevado pero preciso. Nada de "el universo conspira a tu
 * favor". Más "observa quién observa" que "pide y recibirás".
 *
 * Las referencias son opcionales.
 *
 * Para actualizar: sobrescribe este array antes del 30-dic. La app
 * envía un recordatorio a contacto@estoicismodigital.com esa fecha.
 */

export type MindsetQuote = {
  /** Frase, 60-180 caracteres ideal. Max 240. */
  text: string;
  /** Autor si es cita real; null si es original. */
  author: string | null;
};

export const MINDSET_QUOTES: MindsetQuote[] = [
  { text: "Observa quién observa. Ahí, en ese testigo silencioso, vive la parte de ti que ninguna circunstancia puede tocar.", author: null },
  { text: "Tu cuerpo está en el pasado, pero tu mente puede vivir en el futuro que eliges. Ese es el comienzo de toda manifestación.", author: "Joe Dispenza" },
  { text: "No ensayes hoy la vieja identidad. Cada pensamiento repetido es un voto a favor del yo que quieres dejar atrás.", author: null },
  { text: "El deseo sin fe es solo hambre. Añade convicción y se convierte en el plano de un mundo nuevo.", author: null },
  { text: "Cuida tus pensamientos, porque se vuelven palabras. Cuida tus palabras, porque se vuelven acciones.", author: "Lao Tse" },
  { text: "La gratitud anticipada no es ingenuidad: es la firma energética de quien ya vive en el resultado.", author: null },
  { text: "Eres el observador, no el observado. El dolor pasa frente a ti; tú permaneces.", author: null },
  { text: "Lo que la mente puede concebir y creer, puede lograrlo.", author: "Napoleón Hill" },
  { text: "La meditación no te saca del mundo: te saca de tu reacción al mundo. Y desde ahí, por fin, puedes crear.", author: null },
  { text: "Respira como si cada inhalación fuera una decisión: quiero seguir aquí, consciente, despierto.", author: null },
  { text: "El subconsciente no discute: repite. Elige con cuidado lo que pones en él antes de dormir.", author: null },
  { text: "Donde pones tu atención, pones tu energía. Donde pones tu energía, construyes tu realidad.", author: "Joe Dispenza" },
  { text: "No eres tu pensamiento. Eres el espacio en el que el pensamiento aparece y se disuelve.", author: "Eckhart Tolle" },
  { text: "El corazón piensa en frecuencias; el cerebro piensa en palabras. Cuando coinciden, el mundo cede.", author: null },
  { text: "Lo que resistes persiste, no porque el universo sea cruel, sino porque tu atención lo mantiene vivo.", author: "Carl Jung" },
  { text: "Entre el estímulo y la respuesta hay un espacio. En ese espacio reside tu poder y tu libertad.", author: "Viktor Frankl" },
  { text: "Nadie es libre si no es dueño de sí mismo.", author: "Epicteto" },
  { text: "La intención es clara; la expectativa es ansiosa. Sabrás la diferencia por cómo respira tu pecho.", author: null },
  { text: "Rendirse no es dejar de actuar: es dejar de empujar lo que ya está hecho en el campo.", author: null },
  { text: "Siéntate en silencio diez minutos. Si no puedes, siéntate veinte. Ahí empieza el entrenamiento real.", author: null },
  { text: "Nuestra vida es lo que nuestros pensamientos la hacen.", author: "Marco Aurelio" },
  { text: "Cada mañana eres un posible: no confundas la memoria con el destino.", author: null },
  { text: "La repetición es la llave del subconsciente. La emoción es la cerradura que se abre.", author: null },
  { text: "No pidas: declara. No supliques: afirma desde el cuerpo del que ya recibió.", author: null },
  { text: "Quien mira hacia afuera sueña; quien mira hacia adentro despierta.", author: "Carl Jung" },
  { text: "La coherencia entre lo que piensas, sientes y haces es la única oración que el campo escucha.", author: null },
  { text: "El ego no es tu enemigo: es una piel vieja. Déjala caer con ternura, no con violencia.", author: null },
  { text: "No eres lo que te pasó. Eres lo que eliges ser desde aquí, con lo que te queda.", author: "Carl Jung" },
  { text: "Un pensamiento repetido mil veces con emoción se convierte en una orden al cuerpo.", author: "Joe Dispenza" },
  { text: "La fortuna favorece a los audaces, pero solo cuando la audacia nace de una visión clara.", author: null },
  { text: "Deja de ensayar problemas que todavía no existen: el cuerpo no distingue entre imaginación y realidad.", author: null },
  { text: "El presente es el único lugar donde puedes crear. El pasado ya sucedió; el futuro aún no.", author: null },
  { text: "Cuando el pensamiento calla, algo más antiguo que el pensamiento empieza a hablarte.", author: null },
  { text: "La abundancia no es lo que posees: es la frecuencia desde la que miras lo que ya está aquí.", author: null },
  { text: "Antes de pedir algo al mundo, pregúntate si eres la persona que podría recibirlo sin destruirlo.", author: null },
  { text: "La paciencia es una forma de fe. Es decirle al tiempo: yo sé lo que viene, aunque no lo vea.", author: null },
  { text: "Si cambias tu energía, cambias tu vida. No al revés.", author: "Joe Dispenza" },
  { text: "La vida no se mide en años, sino en momentos en los que estuviste realmente presente.", author: null },
  { text: "El silencio no es ausencia de ruido: es presencia de ti.", author: null },
  { text: "Nada externo puede perturbarte si tu centro está anclado en algo eterno.", author: null },
  { text: "Cada día es una vida en miniatura. Dormirse es morir; despertar es renacer con una decisión nueva.", author: "Arthur Schopenhauer" },
  { text: "La mente que nunca fue entrenada es un caballo sin jinete: correrá, pero no hacia donde tú quieres.", author: null },
  { text: "Observa el pensamiento sin juzgarlo. En el instante en que lo observas, ya no te gobierna.", author: "Jiddu Krishnamurti" },
  { text: "Todo lo que el hombre puede imaginar, otro hombre puede hacerlo real.", author: "Julio Verne" },
  { text: "La manifestación no es magia: es coherencia sostenida en el tiempo hasta que la materia cede.", author: null },
  { text: "Deja de buscar motivación. Construye identidad. La identidad mueve lo que la motivación no alcanza.", author: null },
  { text: "El miedo es imaginación mal dirigida. Redirige el mismo músculo hacia lo que sí quieres y llámalo fe.", author: "Napoleón Hill" },
  { text: "Tu energía es tu moneda más cara. No la regales al primero que te reclame.", author: null },
  { text: "Todo ha nacido dos veces: una en la mente, otra en el mundo. La primera es la más importante.", author: null },
  { text: "Cuando meditas, no estás escapando de la vida: estás recordando quién la está viviendo.", author: null },
  { text: "El carácter no se revela en la calma, sino en la manera en que respondes cuando todo se mueve.", author: null },
  { text: "Eres la suma de tus pensamientos dominantes de los últimos cinco años. Cambia esa suma.", author: null },
  { text: "La intuición es la voz baja del alma. Habla una sola vez, y casi siempre con razón.", author: null },
  { text: "Lo que haces cada día importa más que lo que haces de vez en cuando.", author: null },
  { text: "El hombre es el arquitecto de su propio destino.", author: "Appius Claudius" },
  { text: "Respira hondo. En la pausa entre dos respiros vive el silencio del que naces cada vez.", author: null },
  { text: "No confundas movimiento con avance. A veces la mejor acción es una hora quieto escuchándote.", author: null },
  { text: "Lo que sueles repetirte en privado construye lo que serás en público.", author: null },
  { text: "La mente es su propio lugar y, en sí misma, puede hacer del infierno un cielo o del cielo un infierno.", author: "John Milton" },
  { text: "Si nada cambia dentro, nada cambia afuera. La vida es un espejo lento pero exacto.", author: null },
  { text: "Cada emoción es información: no la reprimas, no la sigas. Léela y decide.", author: null },
  { text: "El propósito no se encuentra: se construye con actos pequeños que honran lo que te importa.", author: null },
  { text: "La rendición activa es dejar de pelear con el instante sin dejar de caminar hacia tu visión.", author: null },
  { text: "Cuando agradeces antes de recibir, anuncias al cuerpo que ya está seguro. Y el cuerpo responde.", author: null },
  { text: "Las cosas no son como son: son como tú eres.", author: "Anaïs Nin" },
  { text: "El universo no te responde en palabras: te responde en coincidencias. Aprende a leerlas.", author: null },
  { text: "Todo hombre toma los límites de su propio campo de visión por los límites del mundo.", author: "Arthur Schopenhauer" },
  { text: "Tu rutina matinal es tu voto por la persona que quieres ser. No lo deposites en blanco.", author: null },
  { text: "El mayor acto de poder es elegir tu respuesta cuando todo te empuja a reaccionar.", author: null },
  { text: "No eres el personaje: eres quien lo interpreta. Recuerda quitarte la máscara antes de dormir.", author: null },
  { text: "La frecuencia que emites es el anuncio que el mundo recibe sobre lo que eres.", author: null },
  { text: "Hay un poder infinito dentro de ti, pero no se entrega a quien no se sienta lo suficiente para oírlo.", author: null },
  { text: "La única disciplina que importa es la que sostiene a tu yo futuro cuando tu yo presente quiere rendirse.", author: null },
  { text: "El pensamiento crea mundos. Elige los tuyos con el cuidado de un arquitecto, no con la prisa de un turista.", author: null },
  { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi" },
  { text: "Si quieres saber cómo está tu alma, escucha con qué hablas contigo cuando nadie te oye.", author: null },
  { text: "La quietud no es pasividad: es la forma más concentrada de acción interior.", author: null },
  { text: "Nada se pierde cuando se invierte en consciencia. Todo lo demás es préstamo.", author: null },
  { text: "Un deseo ardiente es el punto de partida de todo logro, no la esperanza, no el deseo, sino el ansia palpitante.", author: "Napoleón Hill" },
  { text: "El sexto sentido no aparece cuando lo buscas: aparece cuando por fin dejas de hacer ruido.", author: null },
  { text: "Cada mañana, elige tres palabras que definan a la persona que serás hoy. Vive desde ellas.", author: null },
  { text: "Hay un poder mayor operando a través de ti. Tu único trabajo es dejar de bloquearlo con miedo.", author: null },
  { text: "La persona que serás dentro de cinco años está escribiendo hoy su biografía con lo que decides repetir.", author: null },
  { text: "El silencio es la lengua materna del alma.", author: "Rumi" },
  { text: "Lo que no integras, lo repites. Lo que no observas, te gobierna. Lo que no nombras, te define.", author: null },
  { text: "La meditación es el arte de quedarse con uno mismo sin huir hacia el teléfono.", author: null },
  { text: "No dejes que la urgencia del mundo mate la importancia de tu silencio.", author: null },
  { text: "Una mente enfocada es más poderosa que un ejército disperso.", author: null },
  { text: "Todo es energía, y eso es todo lo que hay que entender.", author: "Albert Einstein" },
  { text: "Si sientes con anticipación como si ya hubiera ocurrido, el cuerpo se convierte en el evento.", author: "Joe Dispenza" },
  { text: "Elige tus batallas internas con más cuidado que las externas: ahí se decide todo lo demás.", author: null },
  { text: "El que no busca, no encuentra; pero el que busca con ansiedad, tampoco. Busca con calma atenta.", author: null },
  { text: "La autosugestión es tu conversación privada con tu creador interno. Háblale con respeto y certeza.", author: null },
  { text: "Quien se conoce a sí mismo no necesita que el mundo lo defina.", author: null },
  { text: "El cambio duele solo cuando te agarras al pasado como si fuera una balsa en medio del océano.", author: null },
  { text: "Entrena tu mente como entrenas tu cuerpo: con constancia y sin dramatizar cada mala sesión.", author: null },
  { text: "Lo que piensas de ti mismo es infinitamente más importante que lo que otros piensan de ti.", author: "Séneca" },
  { text: "La vida no te da lo que pides: te da lo que vibras.", author: null },
  { text: "La coherencia del corazón ordena al cerebro; el cerebro ordenado ordena la vida.", author: null },
  { text: "Todo acto de disciplina es un acto de amor propio diferido.", author: null },
  { text: "Los pensamientos se convierten en cosas. Si lo ves en tu mente, lo tendrás en tu mano.", author: "Bob Proctor" },
  { text: "La presencia plena no es técnica: es un acto de fidelidad hacia la vida que está pasando ahora.", author: null },
  { text: "Solo hay dos días en el año en los que no puedes hacer nada: ayer y mañana.", author: "Dalái Lama" },
  { text: "Eres el jardinero de tu subconsciente. Lo que riegas crece, seas consciente o no.", author: null },
  { text: "No controlas el viento; controlas la vela. Ajústala con precisión y deja de maldecir la tormenta.", author: null },
  { text: "El mundo que percibes es el reporte que tu cerebro hace de tu estado interno. Cambia el estado.", author: null },
  { text: "Si pudieras ver tu vida con los ojos de tu yo de ochenta años, sabrías exactamente qué elegir hoy.", author: null },
  { text: "Donde los demás ven obstáculos, el hombre entrenado ve ingredientes de su próxima transformación.", author: null },
  { text: "La riqueza empieza con un estado mental, con propósito definido, con poca o ninguna preparación exterior.", author: "Napoleón Hill" },
  { text: "La mente que teme pierde. La mente entrenada observa el miedo pasar como una nube y actúa.", author: null },
  { text: "Lo que te irrita en los demás habla de ti. Lo que admiras en ellos, también. Ambos son mapas.", author: "Carl Jung" },
  { text: "Cada exhalación es una pequeña muerte. Cada inhalación, una pequeña decisión de seguir creando.", author: null },
  { text: "El futuro no te pertenece: tú te construyes hacia él. Camínalo con la reverencia de quien sabe.", author: null },
  { text: "No puedes pensar tu camino a una vida nueva: tienes que sentirlo antes de que exista.", author: "Joe Dispenza" },
  { text: "La gratitud es la memoria del corazón.", author: "Jean-Baptiste Massieu" },
  { text: "Cuando haces las paces contigo mismo, el mundo deja de ser tu enemigo y se convierte en tu aliado.", author: null },
  { text: "Tu palabra hablada es un decreto. Que salga de ti lo que estarías dispuesto a vivir cien veces.", author: null },
  { text: "Todo lo que consigues por fuera es un reflejo tardío de lo que construiste por dentro.", author: null },
  { text: "No hay atajo a ningún lugar que valga la pena llegar.", author: "Beverly Sills" },
  { text: "La disciplina sin visión es tortura. La visión sin disciplina es fantasía. Une ambas y se llama destino.", author: null },
  { text: "La calma no es ausencia de tormenta: es saber que tu centro no depende del clima.", author: null },
  { text: "Lo que emites con convicción sostenida, el campo lo organiza a tu alrededor sin pedirte permiso.", author: null },
  { text: "Acepta lo que ya es, actúa sobre lo que puedes, suelta lo que no depende de ti. Esa es toda la sabiduría.", author: null },
  { text: "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.", author: "Marcel Proust" },
  { text: "Tu yo futuro ya decidió. Tu trabajo ahora es ponerte a la altura de esa decisión todos los días.", author: null },
  { text: "La gente que cambia el mundo primero cambia la conversación que tiene consigo en la ducha.", author: null },
  { text: "No busques la luz: quita lo que la bloquea. Lo que queda eres tú.", author: "Rumi" },
  { text: "Meditar es recordarle al cuerpo que no tiene que seguir defendiéndose cuando no hay nada que lo ataque.", author: null },
  { text: "Las emociones no domadas se convierten en la biografía que nunca quisiste firmar.", author: null },
  { text: "El éxito no se persigue: se atrae convirtiéndote en la persona a la que las oportunidades no pueden ignorar.", author: "Jim Rohn" },
  { text: "La constancia es el idioma con el que el subconsciente aprende a confiar en ti.", author: null },
  { text: "No naciste para encajar: naciste para coincidir contigo mismo. Eso es suficiente.", author: null },
  { text: "El que controla su mente controla sus días. El que controla sus días controla su vida.", author: null },
  { text: "Lo que piensas, lo que sientes y lo que haces: cuando los tres están alineados, ocurren milagros ordinarios.", author: null },
  { text: "Siempre que puedas, elige el silencio antes que la explicación. El silencio enseña más rápido.", author: null },
  { text: "Mientras el guerrero sostiene su espada, el sabio sostiene su respiración.", author: null },
  { text: "La creación comienza cuando dejas de reaccionar al ruido externo y empiezas a sostener una frecuencia.", author: null },
  { text: "La aceptación no es resignación: es la lucidez que libera energía para lo que sí puedes transformar.", author: null },
  { text: "La felicidad es un subproducto de una vida bien vivida, no el objetivo que persigues empujando todo.", author: "Eleanor Roosevelt" },
  { text: "Afirma tu deseo por escrito cada noche. El papel no recuerda: es tu mente la que se reprograma.", author: null },
  { text: "No te conviertes en lo que deseas: te conviertes en lo que repites con convicción.", author: null },
  { text: "Lo que busca está buscándote.", author: "Rumi" },
  { text: "Hay dos errores en el camino a la consciencia: no empezar, y no seguir.", author: null },
  { text: "El presente es regalo suficiente. Dejar de tratarlo como sala de espera es el comienzo de todo.", author: null },
  { text: "Siente el cuerpo desde adentro antes de salir al mundo. Es el ancla que ninguna circunstancia puede mover.", author: null },
  { text: "No dejes que un mal día escriba un mal capítulo, ni que un mal capítulo borre un buen libro.", author: null },
  { text: "Quien quiera mover el mundo, primero debe moverse a sí mismo.", author: "Sócrates" },
  { text: "La energía sigue a la atención, y la vida sigue a la energía. Todo empieza por dónde miras.", author: null },
  { text: "Un hombre no es más que el producto de sus pensamientos. Lo que piensa, en eso se convierte.", author: "Mahatma Gandhi" },
  { text: "No eres la historia que tu mente cuenta cuando está asustada. Eres quien decide si escucharla.", author: null },
  { text: "La mente que medita no huye del mundo: vuelve a él con los ojos limpios.", author: null },
  { text: "Todo lo que existe existió primero en el pensamiento de alguien que se atrevió a sostenerlo.", author: null },
  { text: "No es la duración del trabajo interior lo que importa, sino la intensidad sostenida con la que lo haces.", author: null },
  { text: "Despierta curioso, no ansioso. La curiosidad abre puertas; la ansiedad las cierra todas a la vez.", author: null },
  { text: "La fe es la eternidad en el tiempo. Es saber antes de ver.", author: null },
  { text: "Los pequeños hábitos son el sistema operativo invisible de tu destino.", author: null },
  { text: "Cuando aceptas radicalmente lo que hay, algo en el cuerpo se desarma y por fin puedes pensar claro.", author: null },
  { text: "La vida contemplada es la única vida digna de ser vivida.", author: "Sócrates" },
  { text: "No intentes controlar lo que vendrá. Asegura la calidad de quien lo recibirá.", author: null },
  { text: "Nada tan útil como un cuaderno y un bolígrafo al alba: el subconsciente guarda sus mejores regalos ahí.", author: null },
  { text: "Un deseo claro, escrito, leído a diario y sentido, deja de ser fantasía y empieza a ser ruta.", author: null },
  { text: "El que se levanta temprano gana el día. El que medita temprano gana la vida.", author: null },
  { text: "La compasión hacia ti mismo es la raíz del respeto que puedes dar a otros.", author: null },
  { text: "El mundo que ves es el mundo en el que crees. Ampliar la creencia amplía lo que es posible.", author: null },
  { text: "Quien vive en coherencia no tiene que convencer: su vida lo hace por él.", author: null },
  { text: "Cada pensamiento es una semilla. Pregúntate qué bosque quieres habitar dentro de diez años.", author: null },
  { text: "La soledad voluntaria es el taller donde se forja la persona que luego cambia habitaciones enteras.", author: null },
  { text: "Si puedes sentar tu atención en la respiración durante diez minutos, puedes sentarla donde tú decidas.", author: null },
  { text: "El pensamiento es el escultor que puede crear a la persona que quieres ser.", author: "Henry van Dyke" },
  { text: "La prisa es la enemiga silenciosa de la profundidad. No hay manifestación apresurada que dure.", author: null },
  { text: "Cada vez que eliges entre lo correcto y lo cómodo, estás votando por la persona que estás construyendo.", author: null },
  { text: "Nadie puede hacerte sentir inferior sin tu consentimiento.", author: "Eleanor Roosevelt" },
  { text: "El ego quiere tener razón; el alma quiere estar en paz. Elige a conciencia cada mañana.", author: null },
  { text: "Lo que aceptas cambia; lo que rechazas persiste. La aceptación es la palanca más subestimada.", author: null },
  { text: "La eternidad cabe en un instante bien vivido. No acumules días: habita algunos profundamente.", author: null },
  { text: "Si tu voz interior te trata como enemigo, ninguna victoria externa te sentirá a salvo.", author: null },
  { text: "Tu libertad comienza el día que dejas de pedirle permiso a tu mente para sentirte bien.", author: null },
  { text: "El destino no es una cuestión de suerte: es una cuestión de elección. No es algo que se espera, sino algo que se logra.", author: "William Jennings Bryan" },
  { text: "Cuando sincronizas corazón y cerebro, el cuerpo deja de pelearse con el presente. Ahí empieza la magia.", author: null },
  { text: "Observa tus patrones con la curiosidad de un científico, no con la dureza de un juez.", author: null },
  { text: "El sueño sostenido vence al talento desperdiciado siempre que el tiempo sea suficiente.", author: null },
  { text: "Rezar es escuchar, no negociar.", author: null },
  { text: "Lo que no puedes sentir todavía, imagínalo con tal detalle que el cuerpo empiece a ensayarlo.", author: null },
  { text: "La mente es como el agua: cuando está turbulenta, no puedes ver. Cuando está calma, todo se revela.", author: "Prasad Mahes" },
  { text: "El primer acto de poder es cerrar la puerta y quedarte contigo hasta que no haya nadie a quien culpar.", author: null },
  { text: "Ninguna tormenta puede apagarte si tu fuego nace adentro.", author: null },
  { text: "El miedo es una brújula invertida: suele señalar la dirección en la que está tu evolución.", author: null },
  { text: "Todo lo que necesitas hoy ya está dentro de ti; el trabajo es quitar las capas que lo esconden.", author: null },
  { text: "Un hombre con un porqué claro puede soportar casi cualquier cómo.", author: "Viktor Frankl" },
  { text: "La calma disciplinada vence al talento ansioso. Siempre.", author: null },
  { text: "Si no te caes de rodillas al menos una vez al día en asombro, no estás prestando atención.", author: null },
  { text: "Afilar la atención es la única disciplina que mejora todas las demás a la vez.", author: null },
  { text: "No pidas una vida más fácil: pide una versión de ti más capaz. Las dos cosas se parecen al final.", author: null },
  { text: "La intuición no es lógica, pero tampoco es magia. Es sabiduría acumulada que habla sin justificarse.", author: null },
  { text: "Entre tú y tu meta solo hay la persona que todavía no eres. Conviértete en ella hoy, no mañana.", author: null },
  { text: "La paz interior empieza el momento en que decides no dejarle tu poder a ningún evento externo.", author: null },
  { text: "Todo lo que hagas con el corazón alineado se multiplica en el campo. Todo lo demás se evapora.", author: null },
  { text: "Quien gobierna sus emociones gobierna su mundo. Quien las sufre, vive siempre el mundo de otro.", author: null },
  { text: "La mente es una sirvienta excelente y un amo terrible. Decide en qué papel la usas hoy.", author: "Robin Sharma" },
  { text: "Todo avance importante comienza con una decisión secreta que nadie vio y que lo cambió todo.", author: null },
  { text: "Donde hay fe, hay amor; donde hay amor, hay paz; donde hay paz, está Dios; donde está Dios, no falta nada.", author: null },
  { text: "Tu biografía no es tu biología: los pensamientos repetidos tallan los circuitos, y tú tallas los pensamientos.", author: null },
  { text: "No existe la casualidad: solo causas que todavía no has logrado ver con claridad.", author: null },
  { text: "Si tu entorno interno cambia, tu entorno externo debe reorganizarse para seguirte. Esa es la ley.", author: "Joe Dispenza" },
  { text: "El coraje no es la ausencia de miedo: es la decisión de que algo más importante que el miedo exista en ti.", author: null },
  { text: "Lo que ves en otros con admiración duerme también en ti, esperando el permiso que te niegas.", author: null },
  { text: "La disciplina diaria vence a la inspiración ocasional como la marea vence a la roca: en silencio, siempre.", author: null },
  { text: "Haz del alba tu aliada. Las batallas del día se deciden antes de que el mundo despierte.", author: null },
  { text: "Lo más difícil no es conseguir lo que quieres: es convertirte en alguien capaz de mantenerlo.", author: null },
  { text: "El dolor es inevitable; el sufrimiento es la historia que le añades al dolor cuando resistes.", author: null },
  { text: "La manifestación no es pedir: es recordar lo que ya existe para ti en otro plano y sintonizarte con ello.", author: null },
  { text: "Suelta la necesidad de explicar tu camino. A quien importa entiende, y a quien no importa no debe explicarse.", author: null },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles" },
  { text: "Escríbele una carta a tu yo de dentro de un año. Léela en voz alta. El subconsciente guarda cartas reales.", author: null },
  { text: "Lo que resistes aparece más. Lo que aceptas se transforma. Lo que observas, se disuelve a su tiempo.", author: null },
  { text: "Respira por la nariz, lento, profundo, hasta que el diafragma se ría de tu ansiedad.", author: null },
  { text: "No midas el día por lo que produjiste, sino por cuántas veces volviste a tu centro sin avergonzarte.", author: null },
  { text: "La persona que quieres ser ya existe en alguna línea de tu imaginación. Elige habitarla todos los días.", author: null },
  { text: "Cuando la mente se aquieta, el corazón habla. Cuando el corazón habla, la vida se ordena.", author: null },
  { text: "Un minuto de verdad silencia una hora de ruido. No necesitas más.", author: null },
  { text: "Hay tres cosas extremadamente duras: el acero, el diamante, y conocerse a uno mismo.", author: "Benjamin Franklin" },
  { text: "El cambio duradero ocurre cuando la visión de quien serás se vuelve más fuerte que el hábito de quien fuiste.", author: null },
  { text: "Si lo que haces no alimenta tu alma, tarde o temprano te cobrará con síntomas que no sabrás explicar.", author: null },
  { text: "Una mente abierta no es la que cree cualquier cosa: es la que puede sostener una idea sin defenderla.", author: null },
  { text: "La felicidad no es tener lo que quieres: es desear lo que tienes con plena consciencia de su regalo.", author: null },
  { text: "Lo que das al mundo regresa con intereses. Asegúrate de que valga la pena que vuelva multiplicado.", author: null },
  { text: "La meditación no te hace mejor: te revela lo que ya eres cuando dejas de pelearte contigo.", author: null },
  { text: "Atrévete a imaginar sin culpa. La culpa es la policía interna que le sirve a tu antigua identidad.", author: null },
  { text: "El campo cuántico responde a la emoción elevada más que a la palabra exacta. Siente primero, formula después.", author: null },
  { text: "No hay fracaso mientras sigas aprendiendo. Hay fracaso solo cuando dejas de observar tus propios errores.", author: null },
  { text: "Di siempre la verdad: así no tendrás que recordar lo que dijiste.", author: "Mark Twain" },
  { text: "La gratitud es el antídoto más rápido contra la queja. Úsala tres veces al día en ayunas.", author: null },
  { text: "No te conviertes en lo que quieres: te conviertes en lo que te permites sostener como posibilidad real.", author: null },
  { text: "La única comparación útil es entre quien fuiste ayer y quien eliges ser hoy. El resto es ruido.", author: null },
  { text: "Entrenar la atención es el único trabajo que paga dividendos en todas las áreas de la vida.", author: null },
  { text: "Nunca dejes que el miedo a perder te robe la alegría de ganar en silencio todos los días.", author: null },
  { text: "Cuando respiras con conciencia, recuerdas al cuerpo que la vida no es emergencia constante.", author: null },
  { text: "Vive como si cada pensamiento fuera un decreto. Porque, a la larga, lo es.", author: null },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
  { text: "Tus heridas no te definen: tu manera de habitarlas, sí.", author: null },
  { text: "El éxito es una escalera: no puedes subirla con las manos en los bolsillos.", author: "American proverb" },
  { text: "Cada problema que enfrentas con consciencia se convierte en una capa menos de la ceguera que traías.", author: null },
  { text: "El tiempo bien usado en silencio es más productivo que tres días llenos de actividad sin centro.", author: null },
  { text: "Nunca pidas al mundo que te dé lo que todavía no te das a ti mismo.", author: null },
  { text: "El propósito se cumple en los detalles pequeños, no en las declaraciones grandes.", author: null },
  { text: "Cuando perdonas, no liberas al otro: te liberas a ti del contrato invisible que te ataba a él.", author: null },
  { text: "Todo lo que haces con el cuerpo entero presente cambia la química del resultado. Todo lo demás es parche.", author: null },
  { text: "El alma tiene la edad de las preguntas que todavía se atreve a hacerse.", author: null },
  { text: "La repetición no es aburrimiento: es el camino del maestro. El aficionado cambia todos los días.", author: null },
  { text: "Siéntete a salvo contigo mismo antes de pedirle al mundo que te haga sentir a salvo.", author: null },
  { text: "La coherencia es la forma más elegante del poder.", author: null },
  { text: "No puedes dar lo que no te has dado. Cura primero el manantial y luego ofrece el agua.", author: null },
  { text: "Cuando eliges, el universo se reorganiza. Pero primero tienes que elegir de verdad, no con la boca.", author: null },
  { text: "Una vida examinada se convierte en arte. Una vida no examinada se convierte en rutina dolorosa.", author: "Sócrates" },
  { text: "No esperes condiciones perfectas: crea un estado interno perfecto y trabaja desde ahí.", author: null },
  { text: "Cada noche, antes de dormir, agradece tres cosas y siembra una intención. El subconsciente trabaja mientras duermes.", author: null },
  { text: "La fe es el pájaro que canta cuando todavía está oscuro.", author: "Rabindranath Tagore" },
  { text: "No hay humildad más alta que saber que eres co-creador de tu realidad y asumirlo sin arrogancia.", author: null },
  { text: "El que se conoce es iluminado. El que conoce a otros es sabio. El que se conquista es poderoso.", author: "Lao Tse" },
  { text: "Dale al día la dignidad de empezar sin pantalla. Cinco minutos de silencio pagan por todas las horas que vienen.", author: null },
  { text: "La gratitud enciende el nervio vago y le dice al cuerpo: estás a salvo, puedes crear ahora.", author: null },
  { text: "No hay excusas eternas, solo repetidas. En algún momento decides si te quedas con ellas o las sueltas.", author: null },
  { text: "Tu energía convence más que tus palabras. Cuida qué cuerpo entra al lugar antes que qué dices al llegar.", author: null },
  { text: "Todo lo que agradeces antes de recibir, llega con la firma de quien lo esperaba con calma.", author: null },
  { text: "La virtud no se aprende leyendo: se vuelve carne practicándola, incluso cuando nadie te aplaude.", author: null },
  { text: "El cielo no está arriba ni abajo: está en el centro de quien deja de buscarlo afuera.", author: null },
  { text: "La libertad es la percepción del momento presente sin el peso del pasado ni el miedo al futuro.", author: null },
  { text: "Tu visión es un contrato contigo mismo. Léelo cada mañana hasta que tu cuerpo lo firme en silencio.", author: null },
  { text: "El maestro no se conoce por lo que sabe, sino por cómo permanece cuando todo alrededor tiembla.", author: null },
  { text: "La autodisciplina es libertad disfrazada de esfuerzo.", author: null },
  { text: "Todo lo que haces con amor pleno deja una huella energética imposible de borrar.", author: null },
  { text: "La ansiedad es el pasado invadiendo el presente con ropa de futuro. Devuélvela a su sitio con una respiración.", author: null },
  { text: "Ni un día sin una línea. Pequeñas constancias construyen catedrales invisibles.", author: "Plinio el Viejo" },
  { text: "Desear sin actuar es mentirle al subconsciente. Y el subconsciente siempre cobra la mentira más tarde.", author: null },
  { text: "El cuerpo recuerda todo lo que la mente finge olvidar. Escúchalo antes de que tenga que gritarte.", author: null },
  { text: "Decir no a lo que te dispersa es decir sí a lo que te centra. Cada no es una oración sin palabras.", author: null },
  { text: "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.", author: "Aristóteles" },
  { text: "No busques iluminación: busca integridad. La iluminación es lo que sobra cuando dejas de mentirte.", author: null },
  { text: "La coincidencia es la forma en que lo invisible guarda el anonimato.", author: "Albert Einstein" },
  { text: "Cada decisión es un voto. Cada día es una elección. Cada año es un balance silencioso.", author: null },
  { text: "La intuición es la consciencia recordando algo que ya sabe. No la desobedezcas dos veces.", author: null },
  { text: "Somos el universo experimentándose a sí mismo. Trátate en consecuencia.", author: "Alan Watts" },
  { text: "No tienes que creer todo lo que piensas. La mente propone, la consciencia dispone.", author: null },
  { text: "Los pensamientos de tus últimos cinco minutos crearon el estado del que lees esto. Medita qué eliges para los próximos.", author: null },
  { text: "No pidas fuerza para cargar: pide sabiduría para soltar lo que ya no debes llevar.", author: null },
  { text: "El poder no es la capacidad de imponerse: es la capacidad de no reaccionar a lo que provoca.", author: null },
  { text: "Tus pensamientos son la tinta con la que escribes el capítulo de mañana. Escribe con tinta limpia.", author: null },
  { text: "El camino de mil millas empieza con un solo paso.", author: "Lao Tse" },
  { text: "La vida es el eco de lo que transmites, con retraso suficiente para que creas que es casualidad.", author: null },
  { text: "Ama tu destino. No porque sea fácil, sino porque aceptándolo dejas de pelearte con la puerta abierta.", author: "Friedrich Nietzsche" },
  { text: "El trabajo interior es el trabajo más rentable de todos, y paga en todas las monedas a la vez.", author: null },
  { text: "Cuando dejas de necesitar que el mundo cambie, el mundo parece cambiar solo. Es otra forma de ver.", author: null },
  { text: "El amor propio no es un lujo: es la infraestructura sobre la que se construye cualquier vida coherente.", author: null },
  { text: "La energía elevada es contagiosa. La baja también. Decide qué quieres contagiar cada día al entrar a tu casa.", author: null },
  { text: "No confundas estar ocupado con estar viviendo. A veces son lo más opuesto posible.", author: null },
  { text: "Tu tiempo es finito. Tu atención, aún más. Trátalos con la dignidad que merecen.", author: null },
  { text: "El mayor descubrimiento de mi generación es que un ser humano puede alterar su vida alterando sus actitudes mentales.", author: "William James" },
  { text: "La visión define el camino; la disciplina lo pavimenta; la fe lo ilumina cuando pierdes la vista.", author: null },
  { text: "Cuando algo te duele mucho, mira si no estarás sosteniéndolo con las dos manos sin darte cuenta.", author: null },
  { text: "Hablar menos, escuchar más. Reaccionar menos, observar más. Querer menos, ser más.", author: null },
  { text: "El alma crece en silencio como las flores en la oscuridad.", author: null },
  { text: "Confía en el proceso que no controlas mientras haces impecablemente lo que sí te corresponde hoy.", author: null }
];
